import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './helpers.js';
import {call,AiError,responseJson} from '../src/ai.ts';
import {drilldown} from '../src/drilldown.ts';
import {discoverRecords} from '../src/discovery.ts';
import {completedResponse,credentials,chatgptStatus,disconnectChatgpt,subscriptionPayload} from '../src/chatgpt.ts';
import {authorizationUrl,callbackCode} from '../scripts/connect-chatgpt.mjs';
const seed=()=>({id:crypto.randomUUID(),key:Buffer.alloc(32,7).toString('base64url'),client_id:'oaiapp_test',host_id:'urn:uuid:test',subject:'owner',email:'owner@example.com',access_token:'subscription-access',refresh_token:'subscription-refresh',expires_at:Date.now()+3600000,model:'allowed-model',scope:'resource.invoke chatgpt.tokens.use.direct',revocation_endpoint:'https://auth.openai.com/revoke'});
const stream=events=>new Response(events.map(e=>`data: ${JSON.stringify(e)}\n\n`).join(''),{headers:{'Content-Type':'text/event-stream'}});
test('completed streamed items survive a terminal response without output; incomplete streams never succeed',async()=>{
 const item={id:'msg_1',type:'message',status:'completed',role:'assistant',content:[{type:'output_text',text:'{"ok":true}'}]};
 const done={type:'response.output_item.done',output_index:0,item};
 for(const output of [null,[],undefined])assert.deepEqual(responseJson(await completedResponse(stream([done,{type:'response.completed',response:{status:'completed',output}}]))),{ok:true});
 await assert.rejects(completedResponse(stream([done])),e=>e.code==='subscription_interrupted_stream');
 await assert.rejects(completedResponse(stream([done,{type:'response.incomplete',response:{status:'incomplete'}}])));
 const final={...item,content:[{type:'output_text',text:'{"final":true}'}]};
 assert.deepEqual(responseJson(await completedResponse(stream([done,{type:'response.completed',response:{status:'completed',output:[final]}}]))),{final:true});
 assert.throws(()=>responseJson({status:'completed',output:[]}),e=>e.code==='empty_output');
 assert.throws(()=>responseJson({output:[{content:[{type:'output_text',text:'{'}]}]}),e=>e.code==='invalid_output');
 assert.throws(()=>responseJson({output:[{content:[{type:'refusal'}]}]}),e=>e.code==='refused');
});
test('subscription discovery and drilldown consume streamed JSON before sparse completion',async t=>{
 const f=await fixture();t.after(f.close);f.env.AI_AUTH_MODE='chatgpt';f.env.CHATGPT_SESSION=JSON.stringify(seed());
 const provider=async(_,options)=>{
  const body=JSON.parse(options.body),input=JSON.parse(body.input[0].content[0].text);
  const value=body.text.format.name==='question_drilldown_v1'?{candidates:[{question:'条件は何か？',content:'条件を比較',reason:'境界の検証',target:'selected',opposite_id:null},{question:'反例はあるか？',content:'反例を比較',reason:'仮説の検証',target:'selected',opposite_id:null}]}:{candidates:[],destination:{theme_id:input.anchor.id,question:input.anchor.title,scope:'対象の条件',exclusions:'',content:null}};
  return stream([{type:'response.output_text.delta',output_index:0,content_index:0,delta:JSON.stringify(value)},{type:'response.output_item.done',output_index:0,item:{id:'msg_1',type:'message',status:'completed',content:[{type:'output_text',text:JSON.stringify(value)}]}},{type:'response.completed',response:{status:'completed',output:null}}]);
 };
 const run=await discoverRecords(f.env,{id:'theme:work',version:1,idempotency_key:'sse-discovery-regression'},provider);assert.equal(run.state,'completed');
 assert.equal((await drilldown(f.env,'theme:work',{version:1},provider)).candidates.length,2);
 assert.equal(f.db.prepare('SELECT count(*) n FROM themes').get().n,6);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,0);
});
test('missing Content-Type accepts completed JSON and chunked SSE only',async()=>{
 const completed={object:'response',status:'completed',output:[]};
 const body=chunks=>new ReadableStream({start(controller){for(const chunk of chunks)controller.enqueue(new TextEncoder().encode(chunk));controller.close();}});
 assert.deepEqual(await completedResponse(new Response(body([JSON.stringify(completed)]))),completed);
 assert.deepEqual(await completedResponse(new Response(body(['\n','da','ta: '+JSON.stringify({type:'response.completed',response:completed})+'\n\n']))),completed);
 for(const text of ['<html>login</html>','arbitrary text','data: '+JSON.stringify({type:'response.output_text.delta',delta:'partial'})+'\n\n',JSON.stringify({...completed,status:'in_progress'})])await assert.rejects(completedResponse(new Response(body([text]))));
});
test('OAuth registration, state and issued client are bound',()=>{const registration={local_host_id:'urn:uuid:test'},attempt={state:'random-state',nonce:'nonce',challenge:'challenge',redirect_uri:'http://127.0.0.1:1455/auth/callback'};const url=authorizationUrl(registration,attempt);assert.equal(url.searchParams.get('client_id'),'dynamic_agent_client');assert.equal(url.searchParams.get('agent_name_hint'),'Book Harvester');assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.throws(()=>callbackCode(new URL(attempt.redirect_uri+'?state=wrong&code=code&issuedclient_id=oaiapp_test'),attempt,registration));assert.deepEqual(callbackCode(new URL(attempt.redirect_uri+'?state=random-state&code=code&issuedclient_id=oaiapp_test'),attempt,registration),{code:'code',client_id:'oaiapp_test'});assert.throws(()=>callbackCode(new URL(attempt.redirect_uri+'?state=random-state&code=code&issuedclient_id=oaiapp_other'),attempt,{...registration,client_id:'oaiapp_saved'}));});
test('subscription payload omits unsupported paid API fields',()=>{const result=subscriptionPayload({input:'private material',max_output_tokens:10,temperature:0,previous_response_id:'old',store:true,model:'paid-model',text:{format:{type:'json_schema'}}},'allowed-model');assert.equal(result.model,'allowed-model');assert.equal(result.store,false);assert.equal(result.stream,true);assert.ok(Array.isArray(result.input));assert.ok(!('max_output_tokens' in result));assert.ok(!('temperature' in result));assert.ok(!('previous_response_id' in result));});
test('only completed SSE succeeds; HTTP 200 failures and truncated streams fail',async()=>{assert.equal((await completedResponse(stream([{type:'response.completed',response:{status:'completed',output:[]}}]))).status,'completed');await assert.rejects(completedResponse(stream([{type:'error',error:{code:'subscription_sharing_usage_limit_exceeded'}}])),e=>e.code==='subscription_sharing_usage_limit_exceeded');await assert.rejects(completedResponse(stream([{type:'response.output_text.delta',delta:'partial'}])),e=>e.code==='subscription_interrupted_stream');await assert.rejects(completedResponse(stream([{type:'response.incomplete',response:{status:'incomplete'}}])));});
test('subscription mode never calls paid key, embeddings or transcription',async()=>{const f=await fixture();try{f.env.AI_AUTH_MODE='chatgpt';f.env.OPENAI_API_KEY='paid-key';let calls=0;const provider=async()=>{calls++;throw Error('must not call');};await assert.rejects(call(f.env,null,'responses','paid-model',{input:'x'},provider),e=>e instanceof AiError&&e.code==='ai_not_configured');f.env.CHATGPT_SESSION=JSON.stringify(seed());for(const endpoint of ['embeddings','audio/transcriptions'])await assert.rejects(call(f.env,null,endpoint,'paid-model',{input:'x'},provider),e=>e instanceof AiError&&e.code.endsWith('_unsupported'));assert.equal(calls,0);let request;await call(f.env,null,'responses','paid-model',{input:'x',max_output_tokens:10},async(url,options)=>{request={url,options};return stream([{type:'response.completed',response:{status:'completed',output:[],usage:{input_tokens:1,output_tokens:2}}}]);});assert.equal(request.options.headers.Authorization,'Bearer subscription-access');assert.equal(JSON.parse(request.options.body).model,'allowed-model');assert.equal(JSON.parse(request.options.body).max_output_tokens,undefined);assert.equal(f.db.prepare('SELECT model FROM ai_calls').get().model,'allowed-model');const row=f.db.prepare('SELECT encrypted FROM chatgpt_sessions').get();assert.ok(!row.encrypted.includes('subscription-access'));assert.ok(!row.encrypted.includes('subscription-refresh'));}finally{await f.close();}});
test('rotating refresh persists encrypted replacement and disconnect cannot resurrect secret seed',async()=>{const f=await fixture();try{f.env.AI_AUTH_MODE='chatgpt';const original=seed();original.expires_at=0;f.env.CHATGPT_SESSION=JSON.stringify(original);let refreshes=0;const provider=async(url,options)=>{refreshes++;assert.equal(new URLSearchParams(options.body).get('client_id'),'oaiapp_test');assert.equal(new URLSearchParams(options.body).has('scope'),false);return Response.json({access_token:'new-access',refresh_token:'new-refresh',expires_in:3600});};assert.equal((await credentials(f.env,provider)).refresh_token,'new-refresh');assert.equal((await credentials(f.env,provider)).access_token,'new-access');assert.equal(refreshes,1);await disconnectChatgpt(f.env,async(url,options)=>{assert.equal(new URLSearchParams(options.body).get('token'),'new-refresh');return new Response(null,{status:200});});await assert.rejects(credentials(f.env,provider),e=>e.code==='subscription_reauth_required');assert.equal((await chatgptStatus(f.env)).state,'disconnected');assert.equal(refreshes,1);}finally{await f.close();}});
test('refresh lease prevents concurrent rotation and permanent rejection blocks until reconnect',async()=>{const f=await fixture();try{f.env.AI_AUTH_MODE='chatgpt';const s=seed();s.expires_at=0;f.env.CHATGPT_SESSION=JSON.stringify(s);let release,started;const inFlight=new Promise(ok=>started=ok),gate=new Promise(ok=>release=ok);const first=credentials(f.env,async()=>{started();await gate;return Response.json({access_token:'rotated',refresh_token:'rotated-refresh',expires_in:3600});});await inFlight;await assert.rejects(credentials(f.env,async()=>{throw Error('second refresh must not run');}),e=>e.code==='subscription_refresh_busy');release();await first;f.db.prepare('DELETE FROM chatgpt_sessions').run();await assert.rejects(credentials(f.env,async()=>new Response(null,{status:400})),e=>e.code==='subscription_reauth_required');assert.equal((await chatgptStatus(f.env)).state,'reauth_required');await assert.rejects(credentials(f.env,async()=>{throw Error('blocked session must not refresh');}),e=>e.code==='subscription_reauth_required');}finally{await f.close();}});
test('JSON transport requires a complete Responses object and rejects errors or partial output',async()=>{const completed={object:'response',status:'completed',output:[{type:'message',content:[{type:'output_text',text:'done'}]}]};assert.deepEqual(await completedResponse(Response.json(completed)),completed);for(const data of [{object:'response',status:'in_progress',output:[]},{status:'completed',output:[]},{object:'response',status:'incomplete',output:[]},{error:{code:'subscription_sharing_usage_limit_exceeded'}}])await assert.rejects(completedResponse(Response.json(data)));});
