import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,result,graphResponse} from './helpers.js';
import {discoverRecords,integrateRecords,readDiscovery} from '../src/discovery.ts';
import {shortlist,selectCandidates} from '../src/classification.js';
import {validateHarvest} from '../src/harvest-contract.js';
function insert(f,id,text,domain='work',lens='constraint',created=0){const h=result();h.extracted_text=text;h.summary=text;h.claims=[{id:'c1',text,conditions:[],evidence:{origin:'user',quote:text,locator:null,certainty:'explicit'}}];h.questions=[];h.concepts=[];h.view_draft=null;h.classification={domain_ids:[domain],lens_ids:[lens]};f.db.prepare("INSERT INTO captures(id,kind,original_text,note,version,created_at,updated_at,mutation_id,request_key,request_hash) VALUES(?,'text',?,'',1,?,?,?,?,'hash')").run(id,text,created,created,id,id);f.db.prepare('INSERT INTO harvests(capture_id,version,result,created_at) VALUES(?,1,?,?)').run(id,JSON.stringify(h),created);}
function output(i){return {changed:true,change_reason:'条件を整理',understanding:[{id:'u1',text:'作成後の検証が制約になる場合がある',interpretation:'ai',period:null,evidence:i.claims.map(c=>({claim_id:c.id,quote:c.evidence.quote,role:'condition'}))}],changes:[],competing:[],conditions:[],questions:[],relations:[],theme_relations:[],view_proposal:null};}
test('fixed classification rejects unknown IDs, allows no lens and keeps legacy harvest readable',()=>{let h=result();h.classification={domain_ids:['technology'],lens_ids:[]};assert.ok(validateHarvest(h));h.classification.domain_ids=['made-up'];assert.throws(()=>validateHarvest(h));assert.deepEqual(validateHarvest(result()).classification,{domain_ids:[],lens_ids:[]});});
test('shortlist preserves cross-domain material; meaningful nearby candidates precede analogies and retain a counterexample',()=>{const a={text:'AI制作検証',domain_ids:['work'],lens_ids:['constraint'],fingerprint:'a'};const rs=Array.from({length:40},(_,i)=>({id:String(i),text:'AI制作',domain_ids:['work'],lens_ids:[],fingerprint:String(i)}));rs.push({id:'cross',text:'漫画の展開を選ぶ',domain_ids:['creation'],lens_ids:['constraint'],fingerprint:'cross'});const pool=shortlist(a,rs);assert.equal(pool.length,30);assert.ok(pool.some(x=>x.id==='cross'));const chosen=selectCandidates(pool.map(x=>({id:x.id,reason:'比較に役立つ',relation:x.id==='cross'?'counterexample':'support',relevance:2})),pool);assert.equal(chosen.length,5);assert.equal(chosen.at(-1).id,'cross');});
test('all history discovery is read-only; integration includes selected and retained evidence, no unselected materials; replay costs no AI',async t=>{const f=await fixture();t.after(f.close);f.env.AI_EXECUTION_POLICY='explicit';insert(f,'anchor','コード作成は速いが検証が残る');insert(f,'old','漫画作成後に展開の選択が残る','creation');insert(f,'near','決算作成後に原資料の確認が残る');insert(f,'unused','GPU通信が性能を制約する','technology');for(let n=0;n<1010;n++)insert(f,`noise${n}`,'関係のない食事の感想','care','personalization',100+n);
 let calls=0;const ai=async(url,options)=>{calls++;const p=JSON.parse(options.body),i=JSON.parse(p.input);if(p.text.format.name==='related_discovery_v1'){assert.equal(i.selection.scanned,1013);assert.ok(i.candidates.some(c=>c.id==='old'));return graphResponse({},{candidates:i.candidates.filter(c=>['old','near','unused'].includes(c.id)).map(c=>({id:c.id,reason:'検証への制約の移動',relation:'condition',relevance:3})),destination:{theme_id:'theme:work',question:'専門性',scope:'仕事',exclusions:''}});}assert.deepEqual(i.selected_ids,['anchor','old']);assert.ok(!i.claims.some(c=>c.capture_id==='near'||c.capture_id==='unused'));return graphResponse({},output(i));};
 let queries=0;const prepare=f.env.DB.prepare.bind(f.env.DB);f.env.DB.prepare=sql=>{queries++;return prepare(sql);};
 const args={id:'anchor',version:1,idempotency_key:'discovery00000001'};const run=await discoverRecords(f.env,args,ai);assert.ok(queries<100,`Discovery made ${queries} queries for 1,014 records`);assert.equal(calls,1);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships').get().n,0);await readDiscovery(f.env,run.id);await discoverRecords(f.env,args,ai);assert.equal(calls,1);
 const ia={discovery_id:run.id,selected_ids:['old'],idempotency_key:'integration000001'};const saved=await integrateRecords(f.env,ia,ai);assert.equal(saved.state,'completed');assert.equal(calls,2);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships').get().n,2);assert.equal(f.db.prepare('SELECT count(*) n FROM views').get().n,0);await integrateRecords(f.env,ia,ai);assert.equal(calls,2);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,1);
});
test('concurrent correction rejects stale AI output and leaves no theme, membership or synthesis',async t=>{const f=await fixture();t.after(f.close);insert(f,'anchor','AI開発で検証が残る');const r=await discoverRecords(f.env,{id:'anchor',version:1,idempotency_key:'discovery00000002'},async()=>graphResponse({},{candidates:[],destination:{theme_id:null,question:'検証は何を制約する？',scope:'検証',exclusions:''}}));await assert.rejects(integrateRecords(f.env,{discovery_id:r.id,selected_ids:[],idempotency_key:'integration000002'},async(url,options)=>{f.db.prepare("UPDATE captures SET version=2 WHERE id='anchor'").run();return graphResponse({},output(JSON.parse(JSON.parse(options.body).input)));}),/更新/);assert.equal(f.db.prepare('SELECT count(*) n FROM themes').get().n,6);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships').get().n,0);});
test('uneven branches combine theme plus capture, preserve originals, and deepen without a new layer',async t=>{
 const f=await fixture();t.after(f.close);insert(f,'a','検証の制約');insert(f,'b','仕事の検証');insert(f,'c','漫画の検証','creation');
 const ai=async(url,options)=>{const p=JSON.parse(options.body),i=JSON.parse(p.input);return graphResponse({},p.text.format.name==='related_discovery_v1'?{candidates:i.candidates.map(c=>({id:c.id,reason:'検証の比較',relation:'condition',relevance:3})),destination:{theme_id:null,question:'検証の制約はどこへ移る？',scope:'検証',exclusions:''}}:output(i));};
 const first=await discoverRecords(f.env,{id:'a',version:1,idempotency_key:'branch-discover-1'},ai);
 const one=await integrateRecords(f.env,{discovery_id:first.id,selected_ids:['b'],idempotency_key:'branch-integrate-1'},ai);
 const next=await discoverRecords(f.env,{id:one.theme_id,version:1,idempotency_key:'branch-discover-2'},ai);
 assert.ok(next.candidates.some(x=>x.id==='c'));
 const two=await integrateRecords(f.env,{discovery_id:next.id,selected_ids:['c'],mode:'parent',idempotency_key:'branch-integrate-2'},ai);
 assert.notEqual(two.theme_id,one.theme_id);
 const children=f.db.prepare('SELECT * FROM knowledge_inputs WHERE parent_id=?').all(two.theme_id);assert.equal(children.length,2);assert.ok(children.some(x=>x.child_id===one.theme_id&&x.child_kind==='theme'));
 assert.equal(f.db.prepare('SELECT count(*) n FROM captures').get().n,3);
 const third=await discoverRecords(f.env,{id:two.theme_id,version:1,idempotency_key:'branch-discover-3'},ai);
 const deep=await integrateRecords(f.env,{discovery_id:third.id,selected_ids:[],mode:'deepen',idempotency_key:'branch-integrate-3'},ai);
 assert.equal(deep.theme_id,two.theme_id);assert.equal(deep.version,2);
 assert.equal(f.db.prepare('SELECT count(*) n FROM knowledge_inputs WHERE parent_revision=(SELECT revision_id FROM theme_syntheses WHERE theme_id=?)').get(two.theme_id).n,2);
});
