import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,json,graphResponse} from './helpers.js';
import {discoverRecords,integrateRecords} from '../src/discovery.ts';
import {readTheme,listThemes} from '../src/themes.ts';
function theme(f,id,question){f.db.prepare("INSERT INTO themes(id,question,scope,exclusions,content,created_by,created_at) VALUES(?,?,'条件','','対象は日本の仕事','user',0)").run(id,question);f.db.prepare("INSERT INTO theme_domains VALUES(?,'work')").run(id);}
const discovery=(relation='same_question')=>async(url,options)=>{const p=JSON.parse(options.body),i=JSON.parse(p.input);assert.equal(p.text.format.name,'related_discovery_v1');assert.equal(i.anchor.id,'theme:work');assert.ok(i.candidates.some(c=>c.id==='theme:duplicate'));assert.ok(i.candidates.length<=30);assert.equal(i.themes.length,1);return graphResponse({},{candidates:[{id:'theme:duplicate',reason:'主題と条件が同じ',relation,relevance:3}],destination:{theme_id:'theme:work',question:i.anchor.title,content:null,scope:'仕事',exclusions:''}});};
test('manual deepening stages a candidate without a link or AI, saves only on explicit choice',async t=>{const f=await fixture();t.after(f.close);await f.login();f.db.prepare("INSERT INTO drilldown_runs VALUES('run','theme:work',1,'[]',0)").run();const added=await f.request('/api/themes/theme%3Awork/drilldown/candidates',json('POST',{run_id:'run',question:'職種で違いはある？',content:'日本の事務職'}));assert.equal(added.status,200);assert.equal((await added.json()).candidates[0].origin,'user');assert.equal(f.db.prepare('SELECT count(*) n FROM question_relations').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM ai_calls').get().n,0);const body={run_id:'run',candidate_index:0};const saved=await (await f.request('/api/themes/theme%3Awork/drilldown/save',json('POST',body))).json();assert.equal((await (await f.request('/api/themes/theme%3Awork/drilldown/save',json('POST',body))).json()).id,saved.id);assert.equal((await readTheme(f.env,saved.id)).theme.content,'日本の事務職');assert.equal(f.db.prepare('SELECT count(*) n FROM question_relations').get().n,1);assert.equal((await f.request('/api/themes/theme%3Awork/drilldown/candidates',json('POST',{run_id:'run',question:' '}))).status,400);f.db.prepare("UPDATE themes SET version=2 WHERE id='theme:work'").run();assert.equal((await f.request('/api/themes/theme%3Awork/drilldown/candidates',json('POST',{run_id:'run',question:'別の子問い'}))).status,409);});
test('identity keeps focus ID, original contents and canonical parent/child links with no new layer or synthesis AI',async t=>{const f=await fixture();t.after(f.close);theme(f,'theme:duplicate','仕事とAI');theme(f,'theme:child','子の問い');theme(f,'theme:parent','親の問い');f.db.prepare("INSERT INTO question_relations VALUES('theme:parent','theme:duplicate','drilldown',0),('theme:duplicate','theme:child','drilldown',0)").run();const run=await discoverRecords(f.env,{id:'theme:work',version:1,idempotency_key:'focus-discover'},discovery());assert.equal(f.db.prepare("SELECT state FROM themes WHERE id='theme:duplicate'").get().state,'active');const before=f.db.prepare('SELECT count(*) n FROM themes').get().n;const args={discovery_id:run.id,selected_ids:['theme:duplicate'],idempotency_key:'focus-integrate'};const r=await integrateRecords(f.env,args,()=>{throw Error('identity must not call synthesis');});assert.equal(r.theme_id,'theme:work');assert.equal(r.identity_only,true);assert.equal(f.db.prepare('SELECT count(*) n FROM themes').get().n,before);assert.equal((await readTheme(f.env,'theme:duplicate')).redirect,'theme:work');assert.equal(f.db.prepare("SELECT content FROM themes WHERE id='theme:duplicate'").get().content,'対象は日本の仕事');const index=await listThemes(f.env);assert.equal(index.themes.find(x=>x.id==='theme:work').integration_count,0);assert.ok(index.branches.some(e=>e.parent_id==='theme:parent'&&e.child_id==='theme:work'));assert.ok(index.branches.some(e=>e.parent_id==='theme:work'&&e.child_id==='theme:child'));assert.equal((await integrateRecords(f.env,args)).id,r.id);assert.equal(f.db.prepare('SELECT count(*) n FROM ai_calls').get().n,1);});
test('identity rejects parent-child collapse without changing either question',async t=>{const f=await fixture();t.after(f.close);theme(f,'theme:duplicate','仕事とAI');f.db.prepare("INSERT INTO question_relations VALUES('theme:work','theme:duplicate','drilldown',0)").run();const run=await discoverRecords(f.env,{id:'theme:work',version:1,idempotency_key:'cycle-discover'},discovery());await assert.rejects(integrateRecords(f.env,{discovery_id:run.id,selected_ids:['theme:duplicate'],idempotency_key:'cycle-integrate'}),/親子/);assert.equal(f.db.prepare("SELECT state FROM themes WHERE id='theme:duplicate'").get().state,'active');assert.equal(f.db.prepare('SELECT count(*) n FROM integration_runs').get().n,0);});
