import {test} from 'node:test';
import assert from 'node:assert/strict';
import {zipSync,strToU8} from 'fflate';
import {makePdf,makeEpub} from './document-fixtures.js';
import {fixture,photo,json,mockAi,graphResponse,graphResult} from './helpers.js';
import {parseDocument} from '../src/import-parsers.ts';
import {isbnFrom,lookupBibliography,processBibliography} from '../src/bibliography.ts';
async function upload(f,name,bytes,mime,key='import-fixture-request-0001'){const form=new FormData();form.append('file',new Blob([bytes],{type:mime}),name);return f.request('/api/imports',{method:'POST',headers:{'Idempotency-Key':key},body:form});}
async function importedMock(url,options){if(url.endsWith('transcriptions'))return mockAi(url,options);const p=JSON.parse(options.body);if(p.text.format.name!=='capture_harvest_v1')return mockAi(url,options);const input=JSON.parse(p.input[0].content[0].text),body=input.original_or_corrected_text;const value=(await mockAi(url,options)).json();const h=await value;const out=JSON.parse(h.output[0].content[0].text);out.extracted_text=body;out.claims[0].text=body;out.claims[0].evidence.quote=body;out.summary=body;return graphResponse({},out);}

test('real PDF/EPUB extraction preserves file positions and leaves unselected material outside AI input',async t=>{
 const epub=await parseDocument('epub',makeEpub());assert.equal(epub.title,'Test book');assert.equal(epub.sections.length,2);assert.ok(!epub.sections[0].body.includes('bad()'));assert.match(epub.sections[1].locator,/two.xhtml/);
 const f=await fixture();t.after(f.close);await f.login();const saved=await upload(f,'book.pdf',makePdf(),'application/pdf');assert.equal(saved.status,201);const {id}=await saved.json();await f.drain();let job=await (await f.request(`/api/imports/${id}`)).json();assert.equal(job.state,'ready');assert.equal(job.items.length,2);assert.equal(f.db.prepare('SELECT count(*) n FROM captures').get().n,0);assert.match(job.items[0].preview,/Supply/);
 assert.equal((await f.request(`/api/imports/${id}/select`,json('POST',{ordinals:[1]}))).status,202);const inputs=[];await f.drain(async(url,opts)=>{inputs.push(String(opts.body));return importedMock(url,opts);});job=await (await f.request(`/api/imports/${id}`)).json();assert.ok(job.items[0].capture_id);assert.equal(job.items[1].capture_id,null);assert.ok(inputs.every(x=>!x.includes('Unread second')));
 const cap=await (await f.request(`/api/captures/${job.items[0].capture_id}`)).json();assert.equal(cap.job.state,'completed');assert.match(cap.import_ref.locator,/PDF page 1/);assert.equal(cap.import_origin,'source');assert.equal((await f.request(`/api/imports/${id}/original`)).status,200);
 const again=await upload(f,'book.pdf',makePdf(),'application/pdf','another-import-fixture-key');assert.equal((await again.json()).id,id);await f.request(`/api/captures/${cap.id}`,json('DELETE',{version:1}));assert.equal((await f.request(`/api/imports/${id}/select`,json('POST',{ordinals:[1]}))).status,400);const exported=await (await f.request('/api/export')).json();assert.ok(exported.import_jobs[0].base64);await f.request(`/api/imports/${id}`,json('DELETE',{}));await f.settle();assert.equal(f.objects.size,0);
});

test('photo batch automatically saves each item, uncertain resends do not duplicate, and failed items can retry alone',async t=>{
 const f=await fixture();t.after(f.close);await f.login();const body=new FormData(),a=photo().get('file');body.append('file',a,'1.png');body.append('file',a,'2.png');const saved=await f.request('/api/imports',{method:'POST',headers:{'Idempotency-Key':'photo-batch-fixture-key'},body});const {id}=await saved.json();
 const put=f.env.ORIGINALS.put;let calls=0;f.env.ORIGINALS.put=async(...args)=>{if(++calls===2)throw Error('temporary-storage-failure');return put(...args);};await f.drain();let job=await (await f.request(`/api/imports/${id}`)).json();assert.equal(job.state,'partial');assert.equal(job.items.filter(i=>i.capture_id).length,1);f.env.ORIGINALS.put=put;
 await f.request(`/api/imports/${id}/retry`,json('POST',{}));await f.drain();job=await (await f.request(`/api/imports/${id}`)).json();assert.equal(job.items.filter(i=>i.capture_id).length,2);assert.equal(f.db.prepare('SELECT count(*) n FROM captures').get().n,2);await f.request(`/api/imports/${id}/retry`,json('POST',{}));await f.drain();assert.equal(f.db.prepare('SELECT count(*) n FROM captures').get().n,2);
});

test('highlight source/user/AI provenance, clipping formats, corrupt archives and inflation limits are explicit',async t=>{
 const exported={format:'book-harvester/highlights-v1',source:{title:'Book'},items:[{text:'Quoted source.',origin:'source',locator:'p.8',note:'My thought.'},{text:'AI answer.',origin:'ai',locator:null}]};const parsed=await parseDocument('json',strToU8(JSON.stringify(exported)));assert.equal(parsed.sections[0].note,'My thought.');assert.equal(parsed.sections[1].origin,'ai');
 const clipping=await parseDocument('clippings',strToU8('Book\n- Your Highlight on page 3 | Added today\n\nQuoted sentence.\n==========\nBook\n- メモ 位置No. 20\n\nMy thought.\n=========='));assert.deepEqual(clipping.sections.map(x=>x.origin),['source','user']);
 await assert.rejects(parseDocument('epub',makeEpub({'../bad.xml':'x'})),/unsafe_archive/);await assert.rejects(parseDocument('epub',makeEpub({'OEBPS/huge.xhtml':'x'.repeat(3*1024*1024)})),/archive_limit/);await assert.rejects(parseDocument('epub',makeEpub({'META-INF/encryption.xml':'<encryption/>'})),/unsupported_epub/);await assert.rejects(parseDocument('json',strToU8('{"format":"unknown"}')),/unsupported_highlights/);
 const f=await fixture();t.after(f.close);await f.login();const saved=await upload(f,'notes.json',strToU8(JSON.stringify(exported)),'application/json');const {id}=await saved.json();await f.drain(importedMock);const job=await (await f.request(`/api/imports/${id}`)).json();const ai=await (await f.request(`/api/captures/${job.items[1].capture_id}`)).json();assert.equal(ai.job.state,'failed');assert.equal(ai.job.error_code,'invalid_import_attribution');assert.equal(ai.import_origin,'ai');assert.equal((await f.request(`/api/imports/${id}/original`)).status,200);
});

test('bibliographic matches preserve uncertainty and dates; lookup failure leaves Capture and Harvest readable',async t=>{
 assert.equal(isbnFrom('ISBN 978-0-14-032872-1'),'9780140328721');assert.equal(isbnFrom('ISBN 9780140328720'),null);
 const candidates=await lookupBibliography('ISBN 9780140328721','Matilda',async()=>Response.json({docs:[{key:'/works/OL45804W',title:'Matilda',author_name:['Roald Dahl'],first_publish_year:1988,edition_key:['OL123M']}]}));assert.equal(candidates[0].match,'isbn');assert.equal(candidates[0].first_publish_year,1988);
 const f=await fixture();t.after(f.close);await f.login();const cap=(await (await f.request('/api/captures',{method:'POST',headers:{'Idempotency-Key':'bibliography-fixture-key'},body:photo()})).json()).id;await f.drain();f.db.prepare("UPDATE bibliography_jobs SET state='pending',available_at=0 WHERE capture_id=?").run(cap);f.db.prepare('DELETE FROM bibliography_cache').run();await processBibliography(f.env,cap,async()=>new Response('offline',{status:503}));const c=await (await f.request(`/api/captures/${cap}`)).json();assert.equal(c.job.state,'completed');assert.ok(c.harvest);assert.equal(f.db.prepare('SELECT error_code FROM bibliography_jobs WHERE capture_id=?').get(cap).error_code,'bibliography_unavailable');
});
