import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,result,graphResponse} from './helpers.js';
import {generateProposals,readProposals,executeProposals,proposalConflict} from '../src/integration-proposals.ts';
function insert(f,id,text,domain='work',lens='constraint',created=0){const h=result();h.extracted_text=text;h.summary=text;h.claims=[{id:'c1',text,conditions:[],evidence:{origin:'user',quote:text,locator:null,certainty:'explicit'}}];h.questions=[];h.concepts=[];h.view_draft=null;h.classification={domain_ids:[domain],lens_ids:[lens]};f.db.prepare("INSERT INTO captures(id,kind,original_text,note,version,created_at,updated_at,mutation_id,request_key,request_hash) VALUES(?,'text',?,'',1,?,?,?,?,'hash')").run(id,text,created,created,id,id);f.db.prepare('INSERT INTO harvests(capture_id,version,result,created_at) VALUES(?,1,?,?)').run(id,JSON.stringify(h),created);}
function output(i){return {changed:true,change_reason:'条件を整理',understanding:[{id:'u1',text:'作成後の検証が制約になる場合がある',interpretation:'ai',period:null,evidence:i.claims.map(c=>({claim_id:c.id,quote:c.evidence.quote,role:'condition'}))}],changes:[],competing:[],conditions:[],questions:[],relations:[],theme_relations:[],view_proposal:null};}
test('saved proposals replay without AI, execute independently and retry only failures',async t=>{
 const f=await fixture();t.after(f.close);for(const mid of ['a','b','c','d'])insert(f,mid,'AI制作の検証 '+mid);let calls=0,failSecond=true;
 const ai=async(url,options)=>{calls++;const payload=JSON.parse(options.body),input=JSON.parse(payload.input);
 if(payload.text.format.name==='integration_proposals_v1')return graphResponse({},{proposals:[['a','b'],['c','d']].map(material_ids=>({material_ids,theme_id:null,question:'検証の役割は？',scope:'制作',exclusions:'',reason:'制約の比較'}))});
 if(input.selected_ids.includes('c')&&failSecond)throw Error('temporary failure');return graphResponse({},output(input));};
 const args={idempotency_key:'batch-proposals-1'};const run=await generateProposals(f.env,args,ai);assert.equal(run.proposals.length,2);assert.equal(calls,1);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,0);
 await readProposals(f.env,run.id);await generateProposals(f.env,args,ai);assert.equal(calls,1);
 const execute={run_id:run.id,selected_ids:run.proposals.map(p=>p.id)};const saved=await executeProposals(f.env,execute,ai);assert.deepEqual(saved.proposals.map(p=>p.state),['completed','failed']);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,1);
 const before=calls;await executeProposals(f.env,execute,ai);assert.equal(calls,before);failSecond=false;const retried=await executeProposals(f.env,{...execute,retry:true},ai);assert.ok(retried.proposals.every(p=>p.state==='completed'));assert.equal(calls,before+1);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,2);
});
test('shared captures allowed; updating a question another proposal reads conflicts',()=>{const a={destination_id:null,materials:[{id:'a'}]},b={destination_id:null,materials:[{id:'a'}]};assert.equal(proposalConflict(a,b),false);a.destination_id='theme:x';b.materials.push({id:'theme:x'});assert.equal(proposalConflict(a,b),true);});
test('unknown AI material IDs fail without saving proposals',async t=>{const f=await fixture();t.after(f.close);insert(f,'a','AI制作');insert(f,'b','AI制作後の検証');await assert.rejects(generateProposals(f.env,{idempotency_key:'batch-invalid'},async()=>graphResponse({},{proposals:[{material_ids:['a','missing'],theme_id:null,question:'問い',scope:'制作',exclusions:'',reason:'比較'}]})),/invalid_proposals/);assert.equal(f.db.prepare('SELECT count(*) n FROM integration_proposals').get().n,0);});
