import {test} from 'node:test';import assert from 'node:assert/strict';
import {fixture,sentence} from './helpers.js';import {callBook} from '../src/book-operations.ts';
async function capture(f,key='theme-test-capture-01'){const c=await callBook(f.env,f.ctx,'save_capture',{text:sentence,source:'供給のしくみ',idempotency_key:key});await callBook(f.env,f.ctx,'extract_record',{id:c.data.id,version:1,idempotency_key:key+'-extract'});await f.drain();return c.data.id;}
function membership(f,theme,cap){f.db.prepare("INSERT INTO theme_memberships VALUES(?,?,1,'[\"c1\"]','fixture','condition','fingerprint','fixture',1)").run(theme,cap);}
test('theme edit preview does not mutate; apply and undo create versions and immutable history',async()=>{
 const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const original=f.db.prepare("SELECT question FROM themes WHERE id='theme:work'").get().question;
 const proposal=await callBook(f.env,f.ctx,'propose_theme_change',{id:'theme:work',version:1,action:'edit',question:'専門性はどこで価値になるか？',reason:'問いを限定',idempotency_key:'theme-edit-proposal-0001'});
 assert.equal(f.db.prepare("SELECT version FROM themes WHERE id='theme:work'").get().version,1);
 await callBook(f.env,f.ctx,'apply_theme_change',{id:proposal.id,idempotency_key:'theme-edit-apply-0001'});assert.equal(f.db.prepare("SELECT version FROM themes WHERE id='theme:work'").get().version,2);
 await callBook(f.env,f.ctx,'undo_theme_change',{id:proposal.id,idempotency_key:'theme-edit-undo-0001'});const restored=f.db.prepare("SELECT * FROM themes WHERE id='theme:work'").get();assert.equal(restored.version,3);assert.equal(restored.question,original);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_history').get().n,2);assert.equal(f.db.prepare('SELECT count(*) n FROM ai_calls').get().n,0);
});
test('theme merge and split preserve memberships and adopted view history through undo',async()=>{
 const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const cap=await capture(f);const adopted=await callBook(f.env,f.ctx,'adopt_view',{id:cap,version:1,idempotency_key:'theme-keep-view-0001'});membership(f,'theme:work',cap);membership(f,'theme:learning',cap);
 const merge=await callBook(f.env,f.ctx,'propose_theme_change',{id:'theme:work',version:1,action:'merge',target_id:'theme:learning',target_version:1,reason:'重なる問いを整理',idempotency_key:'theme-merge-proposal-01'});await callBook(f.env,f.ctx,'apply_theme_change',{id:merge.id,idempotency_key:'theme-merge-apply-0001'});assert.equal(f.db.prepare("SELECT merged_into FROM themes WHERE id='theme:work'").get().merged_into,'theme:learning');await callBook(f.env,f.ctx,'undo_theme_change',{id:merge.id,idempotency_key:'theme-merge-undo-0001'});assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships WHERE capture_id=?').get(cap).n,2);
 const split=await callBook(f.env,f.ctx,'propose_theme_change',{id:'theme:work',version:3,action:'split',question:'別の問い',scope:'限定範囲',capture_ids:[cap],reason:'文脈を分ける',idempotency_key:'theme-split-proposal-01'});await callBook(f.env,f.ctx,'apply_theme_change',{id:split.id,idempotency_key:'theme-split-apply-0001'});const child=split.after.themes.find(t=>!['theme:work','theme:learning'].includes(t.id));assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships WHERE theme_id=?').get(child.id).n,1);await callBook(f.env,f.ctx,'undo_theme_change',{id:split.id,idempotency_key:'theme-split-undo-0001'});assert.equal(f.db.prepare('SELECT state FROM themes WHERE id=?').get(child.id).state,'archived');assert.equal((await callBook(f.env,f.ctx,'get_view',{id:adopted.data.id})).data.version,1);
});
test('theme change checks membership changes even when theme version is unchanged',async()=>{
 const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const cap=await capture(f);
 const proposal=await callBook(f.env,f.ctx,'propose_theme_change',{id:'theme:work',version:1,action:'archive',reason:'整理',idempotency_key:'theme-race-proposal-01'});membership(f,'theme:work',cap);
 await assert.rejects(callBook(f.env,f.ctx,'apply_theme_change',{id:proposal.id,idempotency_key:'theme-race-apply-0001'}),/theme_change_context_changed/);assert.equal(f.db.prepare("SELECT state FROM themes WHERE id='theme:work'").get().state,'active');
});
test('multi-entity search spans old evidence, views and themes without AI and honors visibility',async()=>{
 const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const cap=await capture(f);await callBook(f.env,f.ctx,'adopt_view',{id:cap,version:1,idempotency_key:'search-keep-view-0001'});f.db.prepare('UPDATE captures SET created_at=1 WHERE id=?').run(cap);membership(f,'theme:work',cap);
 const before=f.db.prepare('SELECT count(*) n FROM ai_calls').get().n;const found=await callBook(f.env,f.ctx,'search_records',{entity:'all',query:'供給',limit:50});assert.ok(found.records.some(r=>r.entity==='claim'&&r.created_at===1));assert.ok(found.records.some(r=>r.entity==='view'));assert.ok(found.records.some(r=>r.entity==='concept'));assert.ok(found.records.some(r=>r.entity==='question'));assert.equal(f.db.prepare('SELECT count(*) n FROM ai_calls').get().n,before);
 const themed=await callBook(f.env,f.ctx,'search_records',{entity:'claim',theme_id:'theme:work',until:2});assert.equal(themed.records.length,1);await callBook(f.env,f.ctx,'set_visibility',{entity:'capture',id:cap,version:1,action:'hidden',idempotency_key:'visibility-hide-0001'});assert.equal((await callBook(f.env,f.ctx,'search_records',{query:'供給'})).records.length,0);assert.equal((await callBook(f.env,f.ctx,'search_records',{query:'供給',include_hidden:true})).records.length,1);await callBook(f.env,f.ctx,'set_visibility',{entity:'capture',id:cap,version:1,action:'restore',idempotency_key:'visibility-restore-01'});assert.equal((await callBook(f.env,f.ctx,'search_records',{query:'供給'})).records.length,1);
});
test('MCP deleting a source preserves adopted view revisions and reports deleted evidence',async()=>{
 const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const cap=await capture(f);const adopted=await callBook(f.env,f.ctx,'adopt_view',{id:cap,version:1,idempotency_key:'delete-keep-view-0001'});await callBook(f.env,f.ctx,'delete_capture',{id:cap,version:1,idempotency_key:'delete-source-000001'});const view=await callBook(f.env,f.ctx,'get_view',{id:adopted.data.id});assert.equal(view.status,200);assert.equal(view.data.revisions.length,1);assert.equal(view.data.evidence_issues[0].state,'deleted');const restored=await callBook(f.env,f.ctx,'restore_view',{id:adopted.data.id,version:1,restore_version:1,idempotency_key:'restore-orphan-view-01'});assert.equal(restored.status,200);assert.equal(f.db.prepare('SELECT version FROM views WHERE id=?').get(adopted.data.id).version,2);
});
test('conversation view proposal is grounded and is adopted only by a separate action',async()=>{
 const {dispatchThemes}=await import('../src/themes.ts');const {graphResponse,mockAi}=await import('./helpers.js');const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const cap=await capture(f);membership(f,'theme:work',cap);
 const rebuilt=await callBook(f.env,f.ctx,'rebuild_theme',{id:'theme:work',version:1,idempotency_key:'view-context-rebuild-01'});await f.settle();f.db.prepare('UPDATE theme_jobs SET available_at=0 WHERE id=?').run(rebuilt.job_id);await dispatchThemes(f.env);await f.drain(async(url,options)=>{const p=JSON.parse(options.body);if(p.text?.format?.name!=='theme_synthesis_v1')return mockAi(url,options);const input=JSON.parse(p.input),c=input.claims[0];return graphResponse({}, {changed:true,change_reason:'fixture',understanding:[{id:'u1',text:'供給の制約を見る',interpretation:'ai',period:null,evidence:[{claim_id:c.id,quote:c.evidence.quote,role:'support'}]}],changes:[],competing:[],conditions:[],questions:[],relations:[],theme_relations:[],view_proposal:null});});
 const context=await callBook(f.env,f.ctx,'get_theme_context',{id:'theme:work'}),before=f.db.prepare('SELECT count(*) n FROM ai_calls').get().n;const proposed=await callBook(f.env,f.ctx,'save_view_proposal',{id:'theme:work',version:1,context_token:context.context_token,body:'供給の制約に着目したい。',reason:'会話で検討した案',claim_ids:[context.claims[0].id],idempotency_key:'conversation-view-proposal-01'});assert.equal(proposed.adopted,false);assert.equal(f.db.prepare('SELECT count(*) n FROM views').get().n,0);await callBook(f.env,f.ctx,'adopt_theme_view',{id:'theme:work',proposal_id:proposed.id,action:'adopt',idempotency_key:'conversation-view-adopt-01'});assert.equal(f.db.prepare('SELECT count(*) n FROM views').get().n,1);assert.equal(f.db.prepare('SELECT count(*) n FROM ai_calls').get().n,before);
 const evidence=await callBook(f.env,f.ctx,'get_evidence',{id:context.claims[0].id});assert.equal(evidence.valid,true);assert.equal(evidence.claim.evidence.quote,sentence);
});
test('theme job cancel prevents queued execution and an explicit retry resumes it',async()=>{
 const f=await fixture();f.env.AI_EXECUTION_POLICY='explicit';const scheduled=await callBook(f.env,f.ctx,'rebuild_theme',{id:'theme:work',version:1,idempotency_key:'cancel-theme-schedule-01'});await f.settle();const job=await callBook(f.env,f.ctx,'get_job',{id:scheduled.job_id,kind:'theme'});assert.equal(job.can_cancel,true);await callBook(f.env,f.ctx,'cancel_job',{id:job.id,kind:'theme',version:job.version,idempotency_key:'cancel-theme-operation-01'});await f.drain();assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,0);await callBook(f.env,f.ctx,'retry_job',{id:job.id,kind:'theme',version:job.version,idempotency_key:'retry-theme-operation-001'});await f.drain();assert.equal(f.db.prepare('SELECT state FROM theme_jobs WHERE id=?').get(job.id).state,'completed');
});
