import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,json as plainJson,graphResponse,mockAi,sentence} from './helpers.js';
import {processThemeJob,synthesisInput,relevantViews,dispatchThemes,membershipJobStatement} from '../src/themes.ts';
import {validateSynthesis} from '../src/theme-contract.js';
const json=(method,data)=>{const r=plainJson(method,data);r.headers['Idempotency-Key']=crypto.randomUUID();return r;};
const membership=input=>({memberships:[{theme_id:'theme:work',claim_ids:input.claims.map(c=>c.id),reason:'専門性と仕事の分担を考える材料。',role:'condition'}],candidate:null});
export function synthesis(input){const c=input.claims[0];return {changed:true,change_reason:'成立条件を整理。',understanding:c?[{id:'u1',text:'効果の成立条件を全工程で考える。',interpretation:'ai',period:null,evidence:[{claim_id:c.id,quote:c.evidence.quote,role:'condition'}]}]:[],changes:[],competing:[],conditions:[],questions:[],relations:[],theme_relations:[],view_proposal:null};}
export async function themeAi(url,options){const p=JSON.parse(options.body),input=typeof p.input==='string'?JSON.parse(p.input):null;if(p.text?.format?.name==='theme_membership_v1')return graphResponse({},membership(input));if(p.text?.format?.name==='theme_synthesis_v1')return graphResponse({},synthesis(input));return mockAi(url,options);}
async function capture(f,body=sentence){const r=await f.request('/api/captures',json('POST',{kind:'text',text:body,source_mode:'none'}));assert.equal(r.status,201);const c=await r.json();await f.drain(themeAi);return c;}
async function synthesize(f,fetcher=themeAi){f.db.prepare("UPDATE theme_jobs SET available_at=0 WHERE kind='synthesis'").run();await dispatchThemes(f.env);await f.drain(fetcher);}
test('seeds have seven domains, six questions and five optional lenses with no invented knowledge',async t=>{const f=await fixture();t.after(f.close);await f.login();const r=await (await f.request('/api/themes')).json();assert.equal(r.domains.length,7);assert.equal(r.themes.length,6);assert.equal(f.db.prepare('SELECT count(*) n FROM lenses').get().n,5);assert.ok(r.themes.every(t=>t.result===null));});
test('automatic association and synthesis, immediate correction invalidation, deletion regeneration',async t=>{const f=await fixture();t.after(f.close);await f.login();const c=await capture(f);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships').get().n,1);await synthesize(f);const r=await (await f.request('/api/themes/theme%3Awork')).json();assert.ok(r.result,JSON.stringify(r));assert.equal(r.revision,1);assert.equal(r.evidence.length,1);assert.equal(r.stale,false);assert.equal(f.db.prepare('SELECT count(*) n FROM views').get().n,0);assert.equal((await (await f.request(`/api/captures/${c.id}`)).json()).themes.length,1);
 assert.equal((await f.request(`/api/captures/${c.id}`,json('PATCH',{version:1,corrected_text:'条件を訂正'}))).status,200);await f.settle();const stale=await (await f.request('/api/themes/theme%3Awork')).json();assert.equal(stale.stale,true);assert.equal(stale.evidence.length,0);assert.equal(stale.result.understanding[0].evidence.length,0);
 assert.equal((await f.request(`/api/captures/${c.id}`,json('DELETE',{version:2}))).status,200);await synthesize(f);const after=await (await f.request('/api/themes/theme%3Awork')).json();assert.equal(after.stale,false);assert.deepEqual(after.result.understanding,[]);});
test('two themes reference one capture, unrelated input stays unassigned',async t=>{const f=await fixture();t.after(f.close);await f.login();const r=await f.request('/api/captures',json('POST',{kind:'text',text:sentence,source_mode:'none'}));const c=await r.json();await f.drain(async(url,options)=>{const p=JSON.parse(options.body);if(p.text?.format?.name==='theme_membership_v1'){const input=JSON.parse(p.input),m=membership(input);m.memberships.push({...m.memberships[0],theme_id:'theme:value'});return graphResponse({},m);}return mockAi(url,options);});assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships WHERE capture_id=?').get(c.id).n,2);assert.equal(f.db.prepare('SELECT count(*) n FROM captures').get().n,1);const other=await f.request('/api/captures',json('POST',{kind:'text',text:'明日牛乳を買う',source_mode:'none'}));const o=await other.json();await f.drain();assert.equal(f.db.prepare('SELECT count(*) n FROM theme_memberships WHERE capture_id=?').get(o.id).n,0);});
test('all-years index retains old materials and old related Views ahead of 1,010 recent records',async t=>{const f=await fixture();t.after(f.close);await f.login();const c=await capture(f);const oldId='11111111-1111-1111-1111-111111111111';f.db.prepare("INSERT INTO views VALUES(?,?,'old','昔の見方','全体の処理能力も見る',1,0)").run(oldId,c.id);f.db.prepare("INSERT INTO theme_view_links VALUES('theme:work',?,'採用根拠')").run(oldId);for(let i=0;i<1010;i++){const cap=`noise-${i}`;f.db.prepare("INSERT INTO captures(id,kind,original_text,note,version,created_at,updated_at,mutation_id,request_key,request_hash) VALUES(?,'text','無関係','',1,?,?,?, ?, 'hash')").run(cap,100+i,100+i,cap,cap);if(i<7)f.db.prepare("INSERT INTO views VALUES(?,? ,?,'近況','無関係な近況',1,?)").run(`v${i}`,cap,`d${i}`,100+i);}
 const selected=await synthesisInput(f.env,'theme:work');assert.ok(selected.claims.some(x=>x.capture_id===c.id));assert.equal((await relevantViews(f.env,['theme:work']))[0].id,oldId);assert.equal(selected.selection.population,'all_years_theme_index');});
test('valid old A/B reconnection accepted; fabricated citation rejected',()=>{const c1={id:'A:1:c1',capture_id:'A',capture_version:1,text:'A',theme_ids:['theme:work'],evidence:{origin:'source',quote:'引用A'}},c2={...c1,id:'B:1:c1',capture_id:'B',evidence:{origin:'source',quote:'引用B'}};const input={theme:{id:'theme:work'},claims:[c1,c2],related_themes:[],lenses:[],views:[]};const output=synthesis(input);output.relations=[{from_id:c1.id,to_id:c2.id,type:'qualifies',reason:'成立条件を補う',conditions:['確認能力が一定'],evidence:[{claim_id:c1.id,quote:'引用A',role:'support'},{claim_id:c2.id,quote:'引用B',role:'condition'}]}];assert.ok(validateSynthesis(output,input));output.relations[0].evidence[0].quote='架空';assert.throws(()=>validateSynthesis(output,input));});
test('same membership replay is idempotent; response based on changed capture cannot commit',async t=>{const f=await fixture();t.after(f.close);await f.login();const c=await capture(f);await synthesize(f);const initial=f.db.prepare("SELECT version FROM theme_jobs WHERE kind='synthesis'").get().version;await membershipJobStatement(f.env,c.id,1).run();await dispatchThemes(f.env);await f.drain(themeAi);assert.equal(f.db.prepare("SELECT version FROM theme_jobs WHERE kind='synthesis'").get().version,initial);
 f.db.prepare("UPDATE theme_jobs SET state='pending',available_at=0,version=version+1 WHERE kind='synthesis'").run();f.db.prepare("UPDATE theme_revisions SET input_fingerprint='force-recompare'").run();const j=f.db.prepare("SELECT id FROM theme_jobs WHERE kind='synthesis'").get();await processThemeJob(f.env,j.id,async(url,options)=>{f.db.prepare("UPDATE captures SET version=version+1 WHERE id=?").run(c.id);return themeAi(url,options);});assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,1);assert.equal(f.db.prepare('SELECT state FROM theme_jobs WHERE id=?').get(j.id).state,'pending');});
test('View proposal writes user View and immutable evidence snapshot only after adoption',async t=>{const f=await fixture();t.after(f.close);await f.login();await capture(f);await synthesize(f,async(url,options)=>{const p=JSON.parse(options.body);if(p.text?.format?.name==='theme_synthesis_v1'){const input=JSON.parse(p.input),s=synthesis(input);s.view_proposal={view_id:null,base_version:null,from_text:'',to_text:'全体の制約も考える。',reason:'条件を原根拠から採用する案',evidence:s.understanding[0].evidence};return graphResponse({},s);}return themeAi(url,options);});assert.equal(f.db.prepare('SELECT count(*) n FROM views').get().n,0);const t1=await (await f.request('/api/themes/theme%3Awork')).json();assert.equal(t1.proposals.length,1,JSON.stringify(t1));const r=await f.request('/api/themes/theme%3Awork/proposals',json('POST',{proposal_id:t1.proposals[0].id,action:'adopt'}));assert.equal(r.status,200,await r.text());assert.equal(f.db.prepare('SELECT count(*) n FROM views').get().n,1);assert.equal(f.db.prepare('SELECT count(*) n FROM view_revisions').get().n,1);});
test('cross-domain Lens retrieval preserves both sides and differences',async t=>{const f=await fixture();t.after(f.close);await f.login();for(const [domain,body]of[['work',sentence],['learning',sentence]]){const opts=json('POST',{text:body});await f.request('/api/captures',opts);await f.drain(async(url,options)=>{const p=JSON.parse(options.body);if(p.text?.format?.name==='theme_membership_v1'){const i=JSON.parse(p.input);return graphResponse({},{memberships:[{theme_id:`theme:${domain}`,claim_ids:i.claims.map(c=>c.id),lens_ids:['constraint'],reason:'制約の所在を比較する材料',role:'condition'}],candidate:null});}return themeAi(url,options);});}const input=await synthesisInput(f.env,'theme:work');assert.ok(input.related_themes.some(t=>t.id==='theme:learning'));assert.ok(input.claims.some(c=>c.theme_ids.includes('theme:learning')));const s=synthesis(input),a=input.claims.find(c=>c.theme_ids.includes('theme:work')),b=input.claims.find(c=>c.theme_ids.includes('theme:learning'));s.theme_relations=[{theme_id:'theme:learning',lens_id:'constraint',common_structure:'供給から選択へ制約が移る仮説',important_difference:'仕事は承認、学習は目標の選択が制約',conditions:['選択側の能力が一定'],evidence:[{claim_id:a.id,quote:a.evidence.quote,role:'condition'},{claim_id:b.id,quote:b.evidence.quote,role:'example'}]}];assert.ok(validateSynthesis(s,input));});
test('AI unavailable keeps originals and seeded themes readable; migration status and overrides are authenticated',async t=>{const f=await fixture({key:''});t.after(f.close);assert.equal((await f.request('/api/themes/migration')).status,401);await f.login();const c=await capture(f);const r=await (await f.request(`/api/captures/${c.id}`)).json();assert.equal(r.original_text,sentence);assert.equal((await (await f.request('/api/themes')).json()).themes.length,6);assert.equal((await f.request('/api/themes/migration',json('POST',{action:'pause'}))).status,200);assert.equal((await (await f.request('/api/themes/migration')).json()).paused,true);assert.equal((await f.request('/api/themes/migration',json('POST',{action:'resume'}))).status,200);});
test('question deletion hides the question and removes explicit structural links',async t=>{const f=await fixture();t.after(f.close);await f.login();f.db.prepare("INSERT INTO question_relations VALUES('theme:work','theme:value','drilldown',1)").run();f.db.prepare("INSERT INTO question_oppositions VALUES('theme:value','theme:work','反対仮説',1)").run();const del=await f.request('/api/themes/theme%3Awork',json('DELETE',{version:1}));assert.equal(del.status,200,await del.text());const index=await (await f.request('/api/themes')).json();assert.equal(index.themes.some(x=>x.id==='theme:work'),false);assert.equal((await f.request('/api/themes/theme%3Awork')).status,404);assert.equal(f.db.prepare("SELECT count(*) n FROM question_relations WHERE parent_id='theme:work' OR child_id='theme:work'").get().n,0);assert.equal(f.db.prepare("SELECT count(*) n FROM question_oppositions WHERE left_id='theme:work' OR right_id='theme:work'").get().n,0);assert.equal(f.db.prepare("SELECT state FROM themes WHERE id='theme:work'").get().state,'deleted');assert.equal(f.db.prepare("SELECT count(*) n FROM theme_history WHERE theme_id='theme:work' AND action='delete'").get().n,1);});
test('theme merge retains old ID redirect and user evidence history',async t=>{const f=await fixture();t.after(f.close);await f.login();await capture(f);await synthesize(f);const merge=await f.request('/api/themes/theme%3Awork/merge',json('POST',{version:1,target_id:'theme:value',reason:'問いの対象範囲を整理'}));assert.equal(merge.status,200,await merge.text());const old=await (await f.request('/api/themes/theme%3Awork')).json();assert.equal(old.redirect,'theme:value');assert.equal(f.db.prepare("SELECT count(*) n FROM theme_memberships WHERE theme_id='theme:value'").get().n,1);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_revisions').get().n,1);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_history').get().n,1);});
test('candidate activation requires distinct material, duplicates reuse one stable question',async t=>{const f=await fixture();t.after(f.close);await f.login();const fetcher=async(url,options)=>{const p=JSON.parse(options.body);if(p.text?.format?.name==='capture_harvest_v1'){const input=JSON.parse(p.input[0].content[0].text),text=input.original_or_corrected_text;return graphResponse({},{source:{title:null,page:null,chapter:null,published_at:null,subject_period:null,certainty:'unknown'},extracted_text:text,summary:text,uncertainties:[],claims:[{id:'c1',text,conditions:[],evidence:{origin:'user',quote:text,locator:null,certainty:'explicit'}}],concepts:[],questions:[],view_draft:null});}if(p.text?.format?.name==='theme_membership_v1'){const i=JSON.parse(p.input),existing=i.themes.find(t=>t.created_by==='ai');return graphResponse({},{memberships:existing?[{theme_id:existing.id,claim_ids:i.claims.map(c=>c.id),reason:'同じ継続的な問いの材料',role:'unresolved'}]:[],candidate:existing?null:{question:'供給の増加で選択の役割はどう変わるか？',scope:'仕事、学習、創作で選択が制約となる条件',exclusions:'供給や選択に関係のない備忘',domain_ids:['work','learning','creation'],claim_ids:i.claims.map(c=>c.id),reason:'複数領域で共通の選択の問い'}});}return themeAi(url,options);};
 for(const body of ['確認が追いつかない','確認が追いつかない','教材を選べない','作品案を選べない']){const r=await f.request('/api/captures',json('POST',{text:body}));assert.equal(r.status,201);await f.drain(fetcher);}
 const candidates=f.db.prepare("SELECT * FROM themes WHERE created_by='ai'").all();assert.equal(candidates.length,1);assert.equal(candidates[0].state,'active');assert.equal(f.db.prepare('SELECT count(DISTINCT fingerprint) n FROM theme_memberships WHERE theme_id=?').get(candidates[0].id).n,3);assert.equal(f.db.prepare('SELECT count(*) n FROM theme_domains WHERE theme_id=?').get(candidates[0].id).n,3);});
