// Full browser/IndexedDB/service-worker validation, entirely synthetic and without external network.
import {createServer} from 'node:http';import {chromium,expect} from '@playwright/test';import {fixture,result,mockAi,graphResponse,reflectionResult,setProviderDouble} from '../test/helpers.js';import {makePdf} from '../test/document-fixtures.js';import {dispatch} from '../src/queue.ts';
const f=await fixture({limit:'1000'});f.env.APP_ORIGIN='http://localhost:8790';let loseResponse=false;
const externalBody='供給不足が続いた場合には、価格が上昇することがある。'.repeat(8);
async function ai(url,opts){if(url.includes('cloudflare-dns.com'))return Response.json({Status:0,Answer:[{type:1,data:'104.18.1.1'}]});if(!url.includes('api.openai.com'))return new Response(`<title>公開の一次資料</title><article>${externalBody}</article>`,{headers:{'Content-Type':'text/html'}});if(url.endsWith('transcriptions'))return mockAi(url,opts);const p=JSON.parse(opts.body);if(p.tools)return Response.json({output:[{action:{sources:[{url:'https://www.boj.or.jp/test'}]}}]});if(p.text?.format?.name==='external_research_v1'){const m=JSON.parse(p.input).materials[0];return graphResponse({}, {summary:'取得本文の条件を確認する',findings:[{text:'供給不足には価格の上昇を伴う場合がある',stance:'qualifies',conditions:['供給不足が続く場合'],evidence:[{material_id:m.id,quote:'供給不足が続いた場合には、価格が上昇することがある。'}],event_at:null,subject_period:null}],gaps:['他の要因は未確認'],next_reading:[{material_id:m.id,reason:'原文の条件を読む'}]});}if(p.text?.format?.name==='concept_edit_v1')return graphResponse({}, {name:'供給能力の制約',meaning:'選んだ文脈の能力不足',reason:'本人がこの文脈を独立させたい',warnings:[]});if(p.text?.format?.name==='capture_harvest_v1'){const input=JSON.parse(p.input[0].content[0].text),h=result(),body=input.original_or_corrected_text||h.extracted_text;h.extracted_text=body;h.summary=body.slice(0,80);h.claims[0].text=body;h.claims[0].evidence.quote=body.slice(0,300);h.source.title='ブラウザ検証用資料';return graphResponse({},h);}return mockAi(url,opts);}
setProviderDouble(ai);
const server=createServer(async(req,res)=>{try{const chunks=[];for await(const c of req)chunks.push(c);const body=Buffer.concat(chunks),request=new Request(f.env.APP_ORIGIN+req.url,{method:req.method,headers:req.headers,...(body.length?{body}:{})}),response=await f.worker.fetch(request,f.env,f.ctx);if(loseResponse&&req.method==='PATCH'){loseResponse=false;res.destroy();}else{res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}await f.drain(ai);}catch(e){if(!res.headersSent&&!res.destroyed){res.writeHead(500);res.end('Fixture failure');}console.error(e.message);}});
await new Promise(resolve=>server.listen(8790,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--single-process','--in-process-gpu','--use-gl=angle','--use-angle=swiftshader']}:{})});const errors=[];
try{const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(f.env.APP_ORIGIN);await page.locator('#password').fill(f.env.APP_PASSWORD);await page.locator('#login-form button').click();await expect(page.locator('#record')).toBeVisible();await page.evaluate(()=>navigator.serviceWorker.ready);await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 // PDF selection leaves unread pages outside Capture and AI.
 await page.locator('#record').click();await page.locator('#capture-mode').selectOption('file');await page.locator('#document-file').setInputFiles({name:'synthetic.pdf',mimeType:'application/pdf',buffer:Buffer.from(makePdf())});await expect(page.getByText('範囲を選択できます',{exact:true})).toBeVisible({timeout:10000});await page.getByText('PDF page 1',{exact:true}).click();await page.locator('input[name="ordinal"][value="1"]').check();await page.locator('#import-select button.primary').click();await expect(page.getByText('PDF page 1 · 保存済み',{exact:true})).toBeVisible({timeout:10000});await page.getByText('PDF page 1 · 保存済み',{exact:true}).click();await page.locator('[data-import-capture]').first().click();await expect(page.locator('h1')).toHaveText('Supply constraint raises price.');if(f.db.prepare('SELECT COUNT(*) AS n FROM captures').get().n!==1)throw Error('Unread PDF page processed');
 // Local graph, accessible evidence and explicit concept split/undo.
 await page.getByText('周辺のつながりを読む・概念を整理する',{exact:true}).click();await page.locator('#open-neighborhood').click();await expect(page.locator('.local-graph')).toBeVisible();if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Local graph overflow');await page.getByText('高度な整理：概念の統合・分割・再構成',{exact:true}).click();await page.locator('input[name="concept-node"]').first().check();await page.locator('#concept-action').selectOption('split');await page.locator('#concept-reason').fill('この資料の文脈だけ区別したい');await page.locator('#concept-form button').click();await page.locator('#concept-apply').click();await expect.poll(()=>f.db.prepare('SELECT COUNT(*) AS n FROM concept_overrides').get().n).toBe(1);
 // Minimal-payload research produces grounded source links.
 await page.getByText('問いを外部資料で確かめる',{exact:true}).click();await page.locator('#research-start').click();await page.locator('#research-question').fill('供給不足と価格の関係は？');await page.locator('#research-form button.primary').click();await expect(page.getByText('調査済み',{exact:true})).toBeVisible({timeout:10000});await expect(page.getByText('供給不足には価格の上昇を伴う場合がある',{exact:true})).toBeVisible();await page.getByText('公開の一次資料 · saved',{exact:true}).click();await expect(page.locator('[data-research-capture]')).toBeVisible();await page.locator('#back').click();
 // Reflection appears without a manual start/end workflow.
 f.db.prepare("UPDATE reflection_jobs SET available_at=0 WHERE scope='session'").run();await dispatch(f.env);await f.drain(ai);await page.reload();await expect(page.locator('[data-reflection]').first()).toBeVisible();await page.locator('[data-reflection]').first().click();await expect(page.getByText('残った問い',{exact:true})).toBeVisible();await page.locator('#back').click();
 // Recent Capture/Views are cached independently of the outbox.
 await page.evaluate(async()=>{const m=await import('/offline.js');const state=await m.deviceRequest('/api/state?q=');await m.cacheRecent(state);});await context.setOffline(true);await page.reload();await expect(page.locator('#record')).toBeVisible();await expect(page.getByText(/オフライン · 端末の読書キャッシュ/)).toBeVisible();
 const offlineText='オフラインで残した本人メモ';await page.locator('#record').click();await page.locator('#capture-mode').selectOption('text');await page.locator('#capture-text').fill(offlineText);await page.locator('#text-form button').click();await expect(page.getByRole('button',{name:new RegExp(offlineText)})).toBeVisible();
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jN1sAAAAASUVORK5CYII=','base64');await page.locator('#record').click();await page.locator('#capture-mode').selectOption('image');await page.locator('#image-file').setInputFiles({name:'offline.png',mimeType:'image/png',buffer:png});await expect(page.getByRole('dialog')).not.toBeVisible();
 const wav=Buffer.alloc(48);wav.write('RIFF',0);wav.write('WAVE',8);await page.locator('#record').click();await page.locator('#capture-mode').selectOption('audio');await page.locator('#audio-file').setInputFiles({name:'offline.wav',mimeType:'audio/wav',buffer:wav});await expect(page.getByRole('dialog')).not.toBeVisible();await page.reload();await expect(page.getByRole('button',{name:new RegExp(offlineText)})).toBeVisible();await expect.poll(()=>page.evaluate(async()=>(await (await import('/offline.js')).pendingOperations()).length)).toBe(3);
 await page.evaluate(async()=>{await (await import('/offline.js')).clearReadingCache();});await expect.poll(()=>page.evaluate(async()=>(await (await import('/offline.js')).pendingOperations()).length)).toBe(3);
 // Quota errors retain earlier originals and do not claim another record was saved.
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='outbox'){IDBObjectStore.prototype.put=original;throw new DOMException('Synthetic quota failure','QuotaExceededError');}return original.apply(this,args);};});await page.locator('#record').click();await page.locator('#capture-mode').selectOption('text');await page.locator('#capture-text').fill('容量不足で未保存');await page.locator('#text-form button').click();await expect(page.locator('#capture-error')).toContainText('保存容量が足りません');await page.locator('#close-dialog').click();
 await context.setOffline(false);await page.evaluate(async()=>{await (await import('/offline.js')).resume();});await expect.poll(()=>page.evaluate(async()=>(await (await import('/offline.js')).pendingOperations()).length)).toBe(0);await page.reload();await expect(page.getByRole('button',{name:new RegExp(offlineText)})).toBeVisible();if(f.db.prepare('SELECT COUNT(*) AS n FROM captures').get().n!==5)throw Error('Offline sync duplicated or lost originals');
 // Concurrent edit retains local and remote copies; user explicitly resolves.
 const cap=f.db.prepare('SELECT id,version FROM captures WHERE original_text=?').get(offlineText);await page.getByRole('button',{name:new RegExp(offlineText)}).click();await context.setOffline(true);await page.getByText('訂正・補足など',{exact:true}).click();await page.locator('#correct').click();await page.locator('#note').fill('端末側の変更');await page.locator('#correction-form button.primary').click();await page.getByText('原資料を読む',{exact:true}).click();await expect(page.getByText('端末側の変更',{exact:true})).toBeVisible();await f.login();const remote=await f.request(`/api/captures/${cap.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:cap.version,note:'別画面の変更'})});if(remote.status!==200)throw Error('Remote edit fixture failed');await context.setOffline(false);await page.evaluate(async()=>{await (await import('/offline.js')).resume();});await expect.poll(()=>page.evaluate(async()=>(await (await import('/offline.js')).pendingOperations()).filter(o=>o.state==='conflict').length)).toBe(1);await page.locator('.menu > summary').click();await page.locator('#device-menu').click();await page.getByText(/競合・端末の内容を保持/).click();await expect(page.getByText('別画面の変更',{exact:true})).toBeVisible();await page.locator('[data-resolve]').click();await page.locator('#resolve-note').fill('両方を確認して残した変更');await page.locator('#resolve-form button.primary').click();await expect.poll(()=>f.db.prepare('SELECT note FROM captures WHERE id=?').get(cap.id).note).toBe('両方を確認して残した変更');
 // Lost response uses the same operation ID, without a second revision.
 const current=f.db.prepare('SELECT version FROM captures WHERE id=?').get(cap.id).version;loseResponse=true;await page.evaluate(async({id,version})=>{const m=await import('/offline.js');await m.deviceRequest(`/api/captures/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({version,note:'応答を失っても一度だけ'})});await m.flush();},{id:cap.id,version:current});await expect.poll(()=>f.db.prepare('SELECT version FROM captures WHERE id=?').get(cap.id).version).toBe(current+1);
 // Observed session expiry locks the reading cache while preserving unsent originals.
 await context.setOffline(true);await page.evaluate(async()=>{await (await import('/offline.js')).deviceRequest('/api/captures',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({text:'認証失効時の未送信メモ'})});});f.db.prepare('DELETE FROM sessions').run();await context.setOffline(false);await page.evaluate(async()=>{await (await import('/offline.js')).resume();});await expect(page.locator('#password')).toBeVisible();await expect.poll(()=>page.evaluate(async()=>{const db=await (await import('/offline.js')).deviceDb();return new Promise(resolve=>{const r=db.transaction('responses','readonly').objectStore('responses').count();r.onsuccess=()=>resolve(r.result);});})).toBe(0);await expect.poll(()=>page.evaluate(async()=>(await (await import('/offline.js')).pendingOperations()).length)).toBe(1);await page.locator('#password').fill(f.env.APP_PASSWORD);await page.locator('#login-form button').click();await expect.poll(()=>f.db.prepare('SELECT COUNT(*) AS n FROM captures WHERE original_text=?').get('認証失効時の未送信メモ').n).toBe(1);
 // Logout clears only the reading cache and blocks old queued data until the same owner reauthenticates.
 await context.setOffline(true);await page.evaluate(async()=>{const m=await import('/offline.js');await m.deviceRequest('/api/captures',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({text:'閉じる前の未送信メモ'})});await m.deviceRequest('/api/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});});await page.reload();await expect(page.locator('#password')).toBeVisible();await context.setOffline(false);await page.locator('#password').fill(f.env.APP_PASSWORD);await page.locator('#login-form button').click();await expect.poll(()=>f.db.prepare('SELECT COUNT(*) AS n FROM captures WHERE original_text=?').get('閉じる前の未送信メモ').n).toBe(1);if(errors.length)throw Error(errors.join('\n'));console.log('Expansion browser checks passed: PDF range, neighborhood/concept apply, grounded research, automatic reflection, offline photo/audio/text across restart, cache/outbox separation, quota, automatic sync, conflict resolution, lost-response replay and logout.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));await f.close();}
