import {discoverRecords} from './discovery.ts';
import {stmt,rows,fail,digest,id,now,text,getCapture} from './core.ts';
import {synthesisInput,dirty,membershipJobStatement,dispatchThemes} from './themes.ts';
import {authorizeAI} from './ai-policy.ts';
import {rebuildGraph} from './graph.ts';
import {dispatch} from './queue.ts';
export async function themeContext(env:Env,id:string){const context=await synthesisInput(env,id);return {...context,context_token:await digest(JSON.stringify(context)),ai_called:false};}
export async function saveAnalysis(env:Env,a:Record<string,unknown>){
 const themeId=text(a.id,100),context=await themeContext(env,themeId);if(context.theme.version!==Number(a.version)||context.context_token!==a.context_token)fail(409,'theme_context_changed');
 const body=text(a.body).trim();if(!body)fail(400,'empty_analysis');const key=text(a.idempotency_key,100),hash=await digest(JSON.stringify(a)),draft=id();
 const old=await stmt(env,'SELECT id,request_hash FROM theme_analysis_drafts WHERE request_key=?',key).first<{id:string;request_hash:string}>();if(old){if(old.request_hash!==hash)fail(409,'idempotency_conflict');return {id:old.id,duplicate:true,integrated:false};}
 const snapshot={theme_version:context.theme.version,synthesis_version:context.previous_version,dependencies:context.dependencies,claims:context.claims,views:context.views,context_token:context.context_token};
 let guard='EXISTS(SELECT 1 FROM themes WHERE id=? AND version=?)';const values:(string|number|null)[]=[themeId,context.theme.version];for(const d of context.dependencies){guard+=' AND EXISTS(SELECT 1 FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version WHERE c.id=? AND c.version=? AND h.result=?)';values.push(d.capture_id,d.version,d.harvest);}
 for(const v of context.views){guard+=' AND EXISTS(SELECT 1 FROM views WHERE id=? AND version=?)';values.push(v.id,v.version);}
 const saved=await stmt(env,`INSERT INTO theme_analysis_drafts(id,theme_id,theme_version,body,references_json,request_key,request_hash,created_at) SELECT ?,?,?,?,?,?,?,? WHERE ${guard}`,draft,themeId,context.theme.version,body,JSON.stringify(snapshot),key,hash,now(),...values).run();if(!saved.meta.changes)fail(409,'theme_context_changed');return {id:draft,origin:'ai_conversation',integrated:false,needs_explicit_rebuild:true,ai_called:false};
}
export async function rebuildTheme(env:Env,ctx:ExecutionContext,a:Record<string,unknown>){const context=await themeContext(env,String(a.id));if(context.theme.version!==Number(a.version))fail(409,'theme_version_conflict');await dirty(env,[context.theme.id],true);const job=await stmt(env,"SELECT id,version FROM theme_jobs WHERE kind='synthesis' AND target_id=?",context.theme.id).first<{id:string;version:number}>();await authorizeAI(env,'synthesis',context.theme.id,job!.version);ctx.waitUntil(dispatchThemes(env));return {accepted:true,job_id:job!.id,stage:'synthesis'};}
export async function discover(env:Env,ctx:ExecutionContext,a:Record<string,unknown>){return discoverRecords(env,a);}
const tables=['discovery_runs','integration_runs','captures','capture_revisions','harvests','sources','views','view_revisions','themes','theme_memberships','theme_revisions','synthesis_evidence','theme_relations','theme_history','theme_overrides','theme_analysis_drafts','concepts','concept_edits','graph_relations','assets'];
export async function exportRecords(env:Env,a:Record<string,unknown>){const entity=String(a.entity||'captures');if(!tables.includes(entity))fail(400,'invalid_export_entity');const cursor=Number(a.cursor||0),limit=Number(a.limit||20);if(!Number.isInteger(cursor)||cursor<0||!Number.isInteger(limit)||limit<1||limit>50)fail(400,'invalid_pagination');const records=await rows<Record<string,unknown>>(env,`SELECT * FROM ${entity} ORDER BY rowid LIMIT ? OFFSET ?`,limit+1,cursor);const data=records.slice(0,limit).map(r=>{const {request_key,request_hash,object_key,...publicRecord}=r;return publicRecord;});return {entity,records:data,next_cursor:records.length>limit?cursor+limit:null,entities:tables,original_files:{method:'authenticated_web_export',url:env.APP_ORIGIN+'/api/export'},ai_called:false};}
