import {rows,fail} from './core.ts';
const projection=`WITH entities AS (
 SELECT 'capture' AS entity,c.id,c.version,c.id AS capture_id,NULL AS theme_id,COALESCE(c.corrected_text,c.original_text)||' '||c.note AS body,s.title AS source_title,c.created_at,COALESCE(c.import_origin,CASE WHEN c.source_id IS NULL THEN 'user' ELSE 'source' END) AS origin,COALESCE(j.state,'saved') AS state FROM captures c LEFT JOIN sources s ON s.id=c.source_id LEFT JOIN jobs j ON j.capture_id=c.id AND j.version=c.version
 UNION ALL SELECT 'claim',c.id||':'||c.version||':'||json_extract(x.value,'$.id'),c.version,c.id,NULL,json_extract(x.value,'$.text'),s.title,c.created_at,json_extract(x.value,'$.evidence.origin'),COALESCE(j.state,'saved') FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version JOIN json_each(h.result,'$.claims') x LEFT JOIN sources s ON s.id=c.source_id LEFT JOIN jobs j ON j.capture_id=c.id AND j.version=c.version
 UNION ALL SELECT 'concept',c.id||':'||c.version||':'||json_extract(x.value,'$.id'),c.version,c.id,NULL,json_extract(x.value,'$.name')||' '||json_extract(x.value,'$.description'),s.title,c.created_at,'ai','saved' FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version JOIN json_each(h.result,'$.concepts') x LEFT JOIN sources s ON s.id=c.source_id
 UNION ALL SELECT 'question',c.id||':'||c.version||':'||json_extract(x.value,'$.id'),c.version,c.id,NULL,json_extract(x.value,'$.text'),s.title,c.created_at,'ai','saved' FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version JOIN json_each(h.result,'$.questions') x LEFT JOIN sources s ON s.id=c.source_id
 UNION ALL SELECT 'view',v.id,v.version,v.capture_id,NULL,v.title||' '||v.body,s.title,v.created_at,'user','saved' FROM views v LEFT JOIN captures c ON c.id=v.capture_id LEFT JOIN sources s ON s.id=c.source_id
 UNION ALL SELECT 'theme',t.id,t.version,NULL,t.id,t.question||' '||COALESCE(t.content,'')||' '||t.scope||' '||t.aliases||' '||COALESCE(r.result,''),NULL,COALESCE(r.created_at,t.created_at),CASE WHEN t.created_by='ai' THEN 'ai' ELSE 'user' END,t.state FROM themes t LEFT JOIN theme_syntheses s ON s.theme_id=t.id LEFT JOIN theme_revisions r ON r.id=s.revision_id WHERE t.state<>'merged'
) `;
export async function searchKnowledge(env:Env,a:Record<string,unknown>){
 const entity=String(a.entity||'capture'),origin=String(a.origin||''),state=String(a.state||''),theme=String(a.theme_id||''),limit=Number(a.limit||20),cursor=Number(a.cursor||0),since=Number(a.since||0),until=Number(a.until||Number.MAX_SAFE_INTEGER);
 if(!['all','capture','claim','concept','question','view','theme'].includes(entity)||origin&&!['user','source','ai'].includes(origin)||!Number.isInteger(limit)||limit<1||limit>50||![cursor,since,until].every(n=>Number.isSafeInteger(n)&&n>=0)||since>until)fail(400,'invalid_search_filter');
 const literal=(v:unknown)=>String(v||'').slice(0,200).replace(/[\\%_]/g,'\\$&'),q='%'+literal(a.query)+'%',source='%'+literal(a.source)+'%';
 const result=await rows(env,projection+`SELECT entity,id,version,capture_id,theme_id,substr(body,1,500) AS preview,source_title,created_at,origin,state FROM entities e WHERE (?='all' OR entity=?) AND (body LIKE ? ESCAPE '\\' OR source_title LIKE ? ESCAPE '\\') AND (?='' OR source_title LIKE ? ESCAPE '\\') AND (?='' OR origin=?) AND (?='' OR state=?) AND created_at>=? AND created_at<=? AND (?='' OR theme_id=? OR EXISTS(SELECT 1 FROM current_theme_memberships m WHERE m.theme_id=? AND m.capture_id=e.capture_id) OR entity='view' AND EXISTS(SELECT 1 FROM theme_view_links l WHERE l.theme_id=? AND l.view_id=e.id)) AND (?=0 OR entity IN('capture','claim','concept','question') AND NOT EXISTS(SELECT 1 FROM current_theme_memberships m WHERE m.capture_id=e.capture_id)) AND (?=1 OR NOT EXISTS(SELECT 1 FROM capture_visibility v WHERE v.capture_id=e.capture_id AND v.hidden=1)) AND (?=1 OR NOT EXISTS(SELECT 1 FROM theme_overrides o WHERE o.theme_id=e.theme_id AND o.item_key='theme' AND o.action='hidden')) ORDER BY created_at DESC,entity,id DESC LIMIT ? OFFSET ?`,entity,entity,q,q,String(a.source||''),source,origin,origin,state,state,since,until,theme,theme,theme,theme,a.unorganized===true?1:0,a.include_hidden===true?1:0,a.include_hidden===true?1:0,limit+1,cursor);
 return {records:result.slice(0,limit),next_cursor:result.length>limit?cursor+limit:null,search_scope:'all_history',method:'sql_literal_multi_entity',ai_called:false,filters:{entity,origin,state,theme_id:theme,since,until,unorganized:a.unorganized===true},limit};
}
