export const toolSpecs = [
 ['get_status','Read implementation capabilities and processing status','book:read',{}],
 ['search_records','Search all saved records without AI. Cursor pagination covers the entire history.','book:read',{query:{type:'string'},cursor:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:50}}],
 ['get_record','Read a record, evidence, and graph','book:read',{id:{type:'string'}}],
 ['save_capture','Save the specified text with optional source; starts the existing ingestion pipeline','book:write',{text:{type:'string'},source:{type:'string'},note:{type:'string'},idempotency_key:{type:'string'}}],
 ['revise_capture','Correct a record at its expected version','book:write',{id:{type:'string'},version:{type:'integer'},corrected_text:{type:'string'},note:{type:'string'},idempotency_key:{type:'string'}}],
 ['adopt_view','Explicitly adopt the record AI draft as the user view','book:write',{id:{type:'string'},version:{type:'integer'},idempotency_key:{type:'string'}}],
 ['get_view','Read a user view and adoption history','book:read',{id:{type:'string'}}],
 ['revise_view','Explicitly edit a user view','book:write',{id:{type:'string'},version:{type:'integer'},body:{type:'string'},reason:{type:'string'},idempotency_key:{type:'string'}}],
 ['get_relations','Read the saved local graph without AI','book:read',{id:{type:'string'}}],
 ['get_job','Read ingestion or research job status','book:read',{id:{type:'string'},kind:{type:'string',enum:['capture','research']}}],
 ['retry_job','Explicitly retry failed ingestion or research','book:write',{id:{type:'string'},version:{type:'integer'},kind:{type:'string',enum:['capture','research']},idempotency_key:{type:'string'}}],
 ['start_research','Explicitly start external research under configured host and AI limits','book:write',{question:{type:'string'},capture_id:{type:'string'},version:{type:'integer'},subject_period:{type:'string'},url:{type:'string'},idempotency_key:{type:'string'}}],
 ['cancel_job','Cancel a research job','book:write',{id:{type:'string'},idempotency_key:{type:'string'}}],
 ['preview_delete','Inspect deletion impact and obtain a short-lived version-bound confirmation','book:manage',{id:{type:'string'},version:{type:'integer'}}],
 ['delete_capture','Permanently delete the previewed record using its confirmation and expected version','book:manage',{id:{type:'string'},version:{type:'integer'},confirmation:{type:'string'},idempotency_key:{type:'string'}}],
 ['get_domains','Read knowledge domains when the theme module is available','book:read',{}],
 ['get_theme','Read theme understanding and evidence when the theme module is available','book:read',{id:{type:'string'}}],
 ['get_migration_status','Read theme migration capabilities','book:read',{}],
 ['get_theme_context','Read saved theme context without AI','book:read',{id:{type:'string'}}],
 ['get_history','Read theme synthesis revisions','book:read',{id:{type:'string'}}],
 ['revise_theme','Explicitly correct theme scope at its expected version','book:write',{id:{type:'string'},version:{type:'integer'},question:{type:'string'},scope:{type:'string'},exclusions:{type:'string'},reason:{type:'string'},idempotency_key:{type:'string'}}],
 ['manage_migration','Explicitly pause, resume or retry the theme migration','book:manage',{action:{type:'string',enum:['pause','resume','retry']},idempotency_key:{type:'string'}}],
] as const;
export const required:Record<string,string[]>={get_record:['id'],save_capture:['text','idempotency_key'],revise_capture:['id','version','idempotency_key'],adopt_view:['id','version','idempotency_key'],get_view:['id'],revise_view:['id','version','body','reason','idempotency_key'],get_relations:['id'],get_job:['id','kind'],retry_job:['id','kind','idempotency_key'],start_research:['question','idempotency_key'],cancel_job:['id','idempotency_key'],preview_delete:['id','version'],delete_capture:['id','version','confirmation','idempotency_key'],get_theme:['id'],get_theme_context:['id'],get_history:['id'],revise_theme:['id','version','idempotency_key'],manage_migration:['action','idempotency_key']};
