import {keyMode,subscriptionMode} from './chatgpt.ts';
import {stmt,rows,id,now,digest,getCapture} from './core.ts';import {call,AiError} from './ai.ts';
const model='text-embedding-3-small',dimensions=256;
export function cosine(a:number[],b:number[]){if(a.length!==b.length||!a.length)return -1;let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return aa&&bb?dot/Math.sqrt(aa*bb):-1;}
async function embed(env:Env,input:string,captureId:string|null,fetcher?:typeof fetch){const data=await call(env,captureId,'embeddings',model,{model,input:input.slice(0,8000),dimensions,encoding_format:'float'},fetcher),vector=data.data?.[0]?.embedding;if(!vector||vector.length!==dimensions||vector.some(x=>!Number.isFinite(x))||!vector.some(x=>x!==0))throw new AiError('invalid_embedding');return vector;}
export async function scheduleEmbedding(env:Env,captureId:string,version:number){if(subscriptionMode(env))return;await stmt(env,`INSERT INTO embedding_jobs(capture_id,version,available_at) VALUES(?,?,?) ON CONFLICT(capture_id) DO UPDATE SET version=excluded.version,state='pending',attempts=0,dispatched_at=NULL,lease_token=NULL,error_code=NULL,available_at=excluded.available_at WHERE version<>excluded.version`,captureId,version,now()).run();}
export async function processEmbedding(env:Env,captureId:string,fetcher?:typeof fetch){const token=id(),job=await stmt(env,`UPDATE embedding_jobs SET state='running',attempts=attempts+1,lease_token=?,lease_until=? WHERE capture_id=? AND state='pending' AND available_at<=? RETURNING version,attempts`,token,now()+180000,captureId,now()).first<{version:number;attempts:number}>();if(!job)return;try{const c=await getCapture(env,captureId);if(!c?.harvest||c.version!==job.version)throw new AiError('superseded');const organized=await rows(env,"SELECT co.name,co.meaning FROM current_graph_nodes n JOIN effective_concept_mentions m ON m.node_id=n.id JOIN concepts co ON co.id=m.effective_id WHERE n.capture_id=? ORDER BY n.id",captureId);const input=JSON.stringify({organized_concepts:organized,summary:c.harvest.summary,claims:c.harvest.claims.map(x=>({text:x.text,conditions:x.conditions})),concepts:c.harvest.concepts.map(x=>({name:x.name,meaning:x.description})),questions:c.harvest.questions.map(x=>x.text)}).slice(0,8000),hash=await digest(input),prior=await stmt(env,'SELECT * FROM embeddings WHERE capture_id=? AND input_hash=? AND model=?',captureId,hash,model).first<{vector_json:string}>(),vector=prior?JSON.parse(prior.vector_json):await embed(env,input,captureId,fetcher);
 const guard="EXISTS(SELECT 1 FROM captures WHERE id=? AND version=?) AND EXISTS(SELECT 1 FROM embedding_jobs WHERE capture_id=? AND lease_token=?)";await env.DB.batch([stmt(env,`INSERT INTO embeddings SELECT ?,?,?,?,?,? WHERE ${guard} ON CONFLICT(capture_id) DO UPDATE SET version=excluded.version,input_hash=excluded.input_hash,model=excluded.model,vector_json=excluded.vector_json,created_at=excluded.created_at WHERE ${guard}`,captureId,job.version,hash,model,JSON.stringify(vector),now(),captureId,job.version,captureId,token,captureId,job.version,captureId,token),stmt(env,"UPDATE embedding_jobs SET state=CASE WHEN version=(SELECT version FROM captures WHERE id=?) THEN 'completed' ELSE 'superseded' END,lease_token=NULL,error_code=NULL WHERE capture_id=? AND lease_token=?",captureId,captureId,token)]);
 }catch(e){const code=e instanceof AiError?e.code:'embedding_failed',blocked=['ai_not_configured','daily_limit'].includes(code),tomorrow=new Date();tomorrow.setUTCHours(24,0,0,0);await stmt(env,"UPDATE embedding_jobs SET state=?,error_code=?,available_at=?,dispatched_at=NULL,lease_token=NULL WHERE capture_id=? AND lease_token=?",code==='superseded'?'superseded':blocked?'blocked':job.attempts<3&&e instanceof AiError&&e.retryable?'pending':'failed',code,code==='daily_limit'?tomorrow.getTime():now()+60000,captureId,token).run();}}
export async function dispatchEmbeddings(env:Env){if(subscriptionMode(env))return;await stmt(env,"UPDATE embedding_jobs SET state=CASE WHEN attempts>=3 THEN 'failed' ELSE 'pending' END,dispatched_at=NULL,lease_token=NULL WHERE state='running' AND lease_until<?",now()).run();await stmt(env,"UPDATE embedding_jobs SET state='pending',dispatched_at=NULL WHERE state='blocked' AND available_at<=? AND ?=1",now(),keyMode(env)?1:0).run();for(const j of await rows<{capture_id:string}>(env,"SELECT capture_id FROM embedding_jobs WHERE state='pending' AND available_at<=? AND (dispatched_at IS NULL OR dispatched_at<?) LIMIT 20",now(),now()-300000)){const claimed=await stmt(env,"UPDATE embedding_jobs SET dispatched_at=? WHERE capture_id=? AND state='pending' AND (dispatched_at IS NULL OR dispatched_at<?) RETURNING capture_id",now(),j.capture_id,now()-300000).first();if(!claimed)continue;try{await env.HARVEST_QUEUE.send({embedding_capture_id:j.capture_id});}catch{await stmt(env,'UPDATE embedding_jobs SET dispatched_at=NULL WHERE capture_id=?',j.capture_id).run();}}}
export async function nearest(env:Env,vector:number[],exclude='',limit=12){const data=await rows<{capture_id:string;vector_json:string}>(env,'SELECT e.capture_id,e.vector_json FROM embeddings e JOIN captures c ON c.id=e.capture_id AND c.version=e.version WHERE e.model=? AND e.capture_id<>? ORDER BY e.created_at DESC LIMIT 1000',model,exclude);return data.map(e=>({capture_id:e.capture_id,score:cosine(vector,JSON.parse(e.vector_json))})).filter(e=>e.score>=0.3).sort((a,b)=>b.score-a.score).slice(0,limit);}
export async function semanticCandidates(env:Env,captureId:string){const c=await stmt(env,'SELECT e.vector_json FROM embeddings e JOIN captures c ON c.id=e.capture_id AND c.version=e.version WHERE c.id=?',captureId).first<{vector_json:string}>();return c?nearest(env,JSON.parse(c.vector_json),captureId,4):[];}
export async function semanticSearch(env:Env,query:string,fetcher?:typeof fetch){if(!query.trim()||!keyMode(env))return {matches:[],state:'lexical'};const hash=await digest(`${model}:${query.trim()}`);try{const cached=await stmt(env,'SELECT vector_json FROM search_vectors WHERE query_hash=? AND created_at>?',hash,now()-86400000).first<{vector_json:string}>(),vector=cached?JSON.parse(cached.vector_json):await embed(env,query.trim(),null,fetcher);if(!cached)await env.DB.batch([stmt(env,'INSERT OR REPLACE INTO search_vectors VALUES(?,?,?)',hash,JSON.stringify(vector),now()),stmt(env,'DELETE FROM search_vectors WHERE created_at<?',now()-86400000)]);return {matches:await nearest(env,vector),state:'semantic'};}catch{return {matches:[],state:'lexical'};}}
