import {drilldownLinks} from './drilldown.ts';
import {questionContent,questionContext} from './question-context.ts';
import {automaticAI,allowedAI,authorizeAI} from './ai-policy.ts';
import {stmt,rows,id,now,digest,getCapture,fail,text,type Harvest,type View} from './core.ts';
import {call,AiError} from './ai.ts';
import {aiConfigured} from './chatgpt.ts';
import {membershipSchema,synthesisSchema,membershipInstructions,synthesisInstructions,validateMembership,validateSynthesis} from './theme-contract.js';

type Theme={id:string;question:string;content:string|null;scope:string;exclusions:string;state:string;version:number;merged_into:string|null;aliases:string};
type ThemeJob={id:string;kind:string;target_id:string;version:number;attempts:number;lease_token:string;state:string};
type Claim=Harvest['claims'][number]&{capture_id:string;capture_version:number;source_title:string|null;theme_ids:string[];material_fingerprint?:string};
type Member={theme_id:string;capture_id:string;capture_version:number;claim_ids:string;reason:string;role:string;fingerprint:string;created_at:number};
type Proof={claim_id:string;quote:string|null;role:string};
type Explanation={id:string;text:string;interpretation:string;period:string|null;evidence:Proof[]};
type Synthesis={changed:boolean;change_reason:string;understanding:Explanation[];changes:Explanation[];competing:Explanation[];conditions:Explanation[];questions:Explanation[];relations:{from_id:string;to_id:string;type:string;reason:string;conditions:string[];evidence:Proof[]}[];theme_relations:{theme_id:string;lens_id:string|null;common_structure:string;important_difference:string;conditions:string[];evidence:Proof[]}[];view_proposal:{view_id:string|null;base_version:number|null;from_text:string;to_text:string;reason:string;evidence:Proof[]}|null};
export const themeLimits={membershipThemes:3,themeCandidates:20,activeThemes:24,activationEvidence:3,materials:12,claims:72,views:6,relatedThemes:3,inputCharacters:150000,batchJobs:10,backfillBatch:20,debounceMs:15000};
const proofId=(cap:string,v:number,local:string)=>`${cap}:${v}:${local}`;
const norm=(v:string)=>v.normalize('NFKC').replace(/\s+/g,' ').trim();
export function membershipJobStatement(env:Env,cap:string,v:number,guard='1',values:(string|number|null)[]=[]){return stmt(env,`INSERT INTO theme_jobs(id,kind,target_id,version,available_at,created_at) SELECT ?,'membership',?,?,?,? WHERE ${guard} ON CONFLICT(kind,target_id) DO UPDATE SET version=excluded.version,state=CASE WHEN theme_jobs.state='running' THEN 'running' ELSE 'pending' END,attempts=CASE WHEN theme_jobs.state='running' THEN theme_jobs.attempts ELSE 0 END,available_at=excluded.available_at,dispatched_at=NULL,error_code=NULL`,id(),cap,v,now(),now(),...values);}
export async function dirty(env:Env,themeIds:string[],explicit=false){if(!automaticAI(env)&&!explicit)return;for(const t of new Set(themeIds))await stmt(env,`INSERT INTO theme_jobs(id,kind,target_id,version,available_at,created_at) VALUES(?,'synthesis',?,1,?,?) ON CONFLICT(kind,target_id) DO UPDATE SET version=version+1,state=CASE WHEN state='running' THEN 'running' ELSE 'pending' END,attempts=CASE WHEN state='running' THEN attempts ELSE 0 END,available_at=excluded.available_at,dispatched_at=NULL,error_code=NULL`,id(),t,now()+themeLimits.debounceMs,now()).run();}
export async function dispatchThemes(env:Env){
 const time=now(),paused=await stmt(env,"SELECT value FROM settings WHERE key='theme_backfill_paused'").first<string>('value');
 await env.DB.batch([
 stmt(env,`UPDATE theme_jobs SET state=CASE WHEN attempts>=3 THEN 'failed' ELSE 'pending' END,error_code='worker_interrupted',lease_token=NULL,dispatched_at=NULL WHERE state='running' AND lease_until<?`,time),
 stmt(env,`UPDATE theme_jobs SET state='pending',attempts=0,error_code=NULL,dispatched_at=NULL WHERE state='blocked' AND ?=1 AND (error_code='ai_not_configured' OR (error_code IN('daily_limit','subscription_sharing_usage_limit_exceeded') AND available_at<=?))`,aiConfigured(env)?1:0,time),
 // Any correction/deletion (including imports/sync) invalidates evidence immediately through read guards.
 stmt(env,`INSERT INTO theme_jobs(id,kind,target_id,version,available_at,created_at) SELECT lower(hex(randomblob(16))),'synthesis',s.theme_id,1,?,? FROM theme_syntheses s WHERE ?=1 AND EXISTS(SELECT 1 FROM theme_dependencies e LEFT JOIN captures c ON c.id=e.capture_id WHERE e.revision_id=s.revision_id AND (c.id IS NULL OR c.version<>e.capture_version)) ON CONFLICT(kind,target_id) DO UPDATE SET state='pending',attempts=0,dispatched_at=NULL WHERE theme_jobs.state='completed'`,time,time,automaticAI(env)?1:0),
 // Bounded resumable backfill of all years; does not depend on graph/embedding availability.
 stmt(env,`INSERT OR IGNORE INTO theme_jobs(id,kind,target_id,version,available_at,created_at) SELECT lower(hex(randomblob(16))),'membership',c.id,c.version,?,? FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version WHERE ?=1 AND NOT EXISTS(SELECT 1 FROM theme_jobs j WHERE j.kind='membership' AND j.target_id=c.id) ORDER BY c.created_at LIMIT 20`,paused==='1'?now()+86400000:time,0,automaticAI(env)?1:0),
 ]);
 const jobs=await rows<ThemeJob>(env,`SELECT * FROM theme_jobs WHERE state='pending' AND (?=1 OR EXISTS(SELECT 1 FROM explicit_ai_actions a WHERE a.kind=theme_jobs.kind AND a.target_id=theme_jobs.target_id AND a.version=theme_jobs.version)) AND (?=0 OR kind<>'membership' OR created_at<>0) AND available_at<=? AND (dispatched_at IS NULL OR dispatched_at<?) ORDER BY created_at LIMIT 10`,automaticAI(env)?1:0,paused==='1'?1:0,time,time-300000);
 for(const j of jobs){if(!await allowedAI(env,j.kind,j.target_id,j.version))continue;const claimed=await stmt(env,`UPDATE theme_jobs SET dispatched_at=? WHERE id=? AND state='pending' AND (dispatched_at IS NULL OR dispatched_at<?) RETURNING id`,time,j.id,time-300000).first();if(!claimed)continue;try{await env.HARVEST_QUEUE.send({theme_job_id:j.id},{contentType:'json'});}catch{await stmt(env,'UPDATE theme_jobs SET dispatched_at=NULL WHERE id=?',j.id).run();}}
}
async function response(env:Env,name:string,schema:unknown,instructions:string,input:unknown,fetcher?:typeof fetch){const serialized=JSON.stringify(input);if(serialized.length>themeLimits.inputCharacters)throw new AiError('theme_context_limit');const data=await call(env,null,'responses',env.OPENAI_MODEL,{model:env.OPENAI_MODEL,store:false,input:serialized,instructions,max_output_tokens:Number(env.AI_MAX_OUTPUT_TOKENS),text:{format:{type:'json_schema',name,strict:true,schema}}},fetcher);if(data.status==='incomplete')throw new AiError('incomplete_output');const b=(data.output||[]).flatMap(o=>o.content||[]);if(b.some(x=>x.type==='refusal'))throw new AiError('refused');try{return JSON.parse(b.filter(x=>x.type==='output_text').map(x=>x.text).join(''));}catch{throw new AiError('invalid_theme_output');}}
function claimList(cap:string,v:number,h:Harvest,title:string|null,themeIds:string[]):Claim[]{return h.claims.map(c=>({...c,id:proofId(cap,v,c.id),capture_id:cap,capture_version:v,source_title:title,theme_ids:themeIds}));}
async function processMembership(env:Env,j:ThemeJob,fetcher?:typeof fetch){
 const c=await getCapture(env,j.target_id);if(!c?.harvest||c.version!==j.version){await retryChanged(env,j);return;}
 const themes=await rows<Theme>(env,"SELECT * FROM themes WHERE state IN('active','candidate') ORDER BY CASE state WHEN 'active' THEN 0 ELSE 1 END,created_at LIMIT 44"),domains=await rows<{id:string}>(env,'SELECT * FROM domains ORDER BY position');
 const claims=claimList(c.id,c.version,c.harvest,c.source_title,[]),input={capture_id:c.id,version:c.version,claims,themes,domains,lenses:await rows<{id:string}>(env,'SELECT * FROM lenses')};
 let result;try{result=validateMembership(await response(env,'theme_membership_v1',membershipSchema,membershipInstructions,input,fetcher),input);}catch(e){if(e instanceof AiError)throw e;throw new AiError('invalid_theme_output');}
 const fingerprint=await digest(norm(c.harvest.extracted_text||c.corrected_text||c.original_text)),before=await rows<Member>(env,'SELECT * FROM theme_memberships WHERE capture_id=?',c.id);
 const guard=`EXISTS(SELECT 1 FROM theme_jobs WHERE id=? AND version=? AND state='running' AND lease_token=?) AND EXISTS(SELECT 1 FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version WHERE c.id=? AND c.version=? AND h.result=?)`;
 const values=[j.id,j.version,j.lease_token,c.id,c.version,JSON.stringify(c.harvest)],statements:D1PreparedStatement[]=[];
 if(result.candidate&&result.memberships.length<3){const k=result.candidate,themeId=`candidate:${await digest(norm(k.question)+'\n'+norm(k.scope))}`;const existing=await stmt(env,'SELECT id,state FROM themes WHERE id=?',themeId).first<{id:string;state:string}>();const count=await stmt(env,"SELECT count(*) AS n FROM themes WHERE state='candidate'").first<{n:number}>();if(existing||(count?.n||0)<themeLimits.themeCandidates){statements.push(stmt(env,`INSERT OR IGNORE INTO themes(id,question,scope,exclusions,state,created_by,created_at) SELECT ?,?,?,?,'candidate','ai',? WHERE ${guard}`,themeId,k.question,k.scope,k.exclusions,now(),...values));for(const d of k.domain_ids)statements.push(stmt(env,`INSERT OR IGNORE INTO theme_domains SELECT ?,? WHERE ${guard}`,themeId,d,...values));result.memberships.push({theme_id:themeId,claim_ids:k.claim_ids,reason:k.reason,role:'unresolved'});}}
 const same=JSON.stringify(before.map(m=>[m.theme_id,m.capture_version,m.claim_ids,m.role,m.fingerprint]).sort())===JSON.stringify(result.memberships.map((m:{theme_id:string;claim_ids:string[];role:string})=>[m.theme_id,c.version,JSON.stringify(m.claim_ids),m.role,fingerprint]).sort());
 if(same){await stmt(env,`UPDATE theme_jobs SET state='completed',lease_token=NULL,error_code=NULL WHERE id=? AND ${guard}`,j.id,...values).run();return;}
 statements.push(stmt(env,`DELETE FROM theme_memberships WHERE capture_id=? AND ${guard}`,c.id,...values));
 for(const m of result.memberships)statements.push(stmt(env,`INSERT INTO theme_memberships(theme_id,capture_id,capture_version,claim_ids,reason,role,fingerprint,processing_version,created_at) SELECT ?,?,?,?,?,?,?,'theme-membership/v1',? WHERE ${guard} AND NOT EXISTS(SELECT 1 FROM theme_overrides WHERE theme_id=? AND item_key=? AND action='hidden')`,m.theme_id,c.id,c.version,JSON.stringify(m.claim_ids),m.reason,m.role,fingerprint,now(),...values,m.theme_id,`capture:${c.id}`));
 statements.push(stmt(env,`UPDATE theme_jobs SET state='completed',lease_token=NULL,error_code=NULL WHERE id=? AND ${guard}`,j.id,...values));
 for(const m of result.memberships)for(const lens of m.lens_ids||[])statements.splice(statements.length-1,0,stmt(env,`INSERT OR IGNORE INTO theme_member_lenses SELECT ?,?,? WHERE ${guard} AND EXISTS(SELECT 1 FROM theme_memberships WHERE theme_id=? AND capture_id=?)`,m.theme_id,c.id,lens,...values,m.theme_id,c.id));
 const saved=await env.DB.batch(statements);if(!saved.at(-1)?.meta.changes){await retryChanged(env,j);return;}
 await stmt(env,`UPDATE themes SET state='active',version=version+1 WHERE state='candidate' AND (SELECT count(DISTINCT fingerprint) FROM current_theme_memberships m WHERE m.theme_id=themes.id)>=? AND (SELECT count(*) FROM themes WHERE state='active')<?`,themeLimits.activationEvidence,themeLimits.activeThemes).run();
 if(automaticAI(env))await stmt(env,`UPDATE graph_jobs SET state='pending',attempts=0,available_at=?,dispatched_at=NULL WHERE capture_id=? AND version=? AND state='completed'`,now(),c.id,c.version).run();
}
export async function relevantViews(env:Env,themeIds:string[],terms:string[]=[],captureIds:string[]=[]){
 const words=[...new Set(terms.map(t=>norm(t).slice(0,60)).filter(t=>t.length>=2))].slice(0,6),like=words.map(w=>`%${w.replace(/[\\%_]/g,'\\$&')}%`);
 return rows<View>(env,`SELECT v.* FROM views v WHERE EXISTS(SELECT 1 FROM theme_view_links l WHERE l.view_id=v.id AND l.theme_id IN(SELECT value FROM json_each(?))) OR v.capture_id IN(SELECT value FROM json_each(?)) ${like.length?`OR ${like.map(()=>"v.body LIKE ? ESCAPE '\\'").join(' OR ')}`:''} ORDER BY CASE WHEN EXISTS(SELECT 1 FROM theme_view_links l WHERE l.view_id=v.id AND l.theme_id IN(SELECT value FROM json_each(?))) THEN 0 WHEN v.capture_id IN(SELECT value FROM json_each(?)) THEN 1 ELSE 2 END,v.created_at DESC LIMIT 6`,JSON.stringify(themeIds),JSON.stringify(captureIds),...like,JSON.stringify(themeIds),JSON.stringify(captureIds));
}
export async function themeCandidateCaptures(env:Env,cap:string,terms:string[]=[]){
 return rows<{capture_id:string}>(env,`SELECT DISTINCT m.capture_id FROM current_theme_memberships m WHERE m.capture_id<>? AND m.theme_id IN(SELECT theme_id FROM current_theme_memberships WHERE capture_id=?) ORDER BY CASE m.role WHEN 'counterexample' THEN 0 WHEN 'condition' THEN 1 ELSE 2 END,m.created_at ASC LIMIT 6`,cap,cap);
}
export async function synthesisInput(env:Env,themeId:string){
 const theme=await stmt(env,'SELECT * FROM themes WHERE id=?',themeId).first<Theme>();if(!theme)throw new AiError('theme_missing');
 const old=await stmt(env,`SELECT r.* FROM theme_syntheses s JOIN theme_revisions r ON r.id=s.revision_id WHERE s.theme_id=?`,themeId).first<{id:string;version:number;result:string;input_fingerprint:string}>();
 const members=await rows<Member>(env,`SELECT * FROM current_theme_memberships WHERE theme_id=? ORDER BY CASE role WHEN 'counterexample' THEN 0 WHEN 'condition' THEN 1 ELSE 2 END,created_at ASC LIMIT 6`,themeId),recent=await rows<Member>(env,'SELECT * FROM current_theme_memberships WHERE theme_id=? ORDER BY created_at DESC LIMIT 4',themeId);
 const prior=old?await rows<Member>(env,`SELECT DISTINCT m.* FROM current_theme_memberships m JOIN synthesis_evidence e ON e.capture_id=m.capture_id AND e.capture_version=m.capture_version WHERE e.revision_id=? AND m.theme_id=? ORDER BY CASE e.role WHEN 'counterexample' THEN 0 WHEN 'condition' THEN 1 ELSE 2 END LIMIT 6`,old.id,themeId):[];
 const selected=[...new Map([...prior,...members,...recent].map(m=>[m.capture_id,m])).values()].slice(0,9);
 const relations=await rows<{id:string;question:string;scope:string;exclusions:string}>(env,`SELECT DISTINCT t.* FROM themes t JOIN current_theme_memberships m ON m.theme_id=t.id WHERE t.state='active' AND t.id<>? AND (m.capture_id IN(SELECT value FROM json_each(?)) OR EXISTS(SELECT 1 FROM theme_member_lenses a JOIN theme_member_lenses b ON b.lens_id=a.lens_id WHERE a.theme_id=? AND b.theme_id=t.id)) LIMIT 3`,themeId,JSON.stringify(selected.map(m=>m.capture_id)),themeId);
 // Add both sides for cross-domain comparison; no recursive synthesis scheduling.
 const cross:Member[]=[];for(const t of relations)cross.push(...await rows<Member>(env,`SELECT * FROM current_theme_memberships WHERE theme_id=? ORDER BY CASE role WHEN 'counterexample' THEN 0 ELSE 1 END,created_at ASC LIMIT 1`,t.id));
 const materials=[...new Map([...selected,...cross].map(m=>[m.capture_id,m])).values()].slice(0,12),claims:Claim[]=[],dependencies:{capture_id:string;version:number;harvest:string}[]=[];
 for(const m of materials){const c=await getCapture(env,m.capture_id);if(!c?.harvest||c.version!==m.capture_version)continue;const ids=await rows<{theme_id:string}>(env,'SELECT theme_id FROM current_theme_memberships WHERE capture_id=?',c.id);const group=claimList(c.id,c.version,c.harvest,c.source_title,ids.map(x=>x.theme_id));if(claims.length+group.length>themeLimits.claims)continue;const fp=await digest(norm(c.harvest.extracted_text||c.corrected_text||c.original_text));claims.push(...group.map(x=>({...x,material_fingerprint:fp})));dependencies.push({capture_id:c.id,version:c.version,harvest:JSON.stringify(c.harvest)});}
 const views=await relevantViews(env,[themeId],claims.map(c=>c.text).slice(0,3),dependencies.map(d=>d.capture_id));
 const total=(await stmt(env,'SELECT count(*) AS n FROM current_theme_memberships WHERE theme_id=?',themeId).first<{n:number}>())?.n||0;
 return {analysis_drafts:await rows(env,'SELECT id,body,origin,references_json,created_at FROM theme_analysis_drafts WHERE theme_id=? ORDER BY created_at DESC LIMIT 10',themeId),theme:questionContext(theme),previous:old?JSON.parse(old.result) as Synthesis:null,previous_version:old?.version||0,previous_id:old?.id||null,claims,views,related_themes:relations,lenses:await rows<{id:string}>(env,'SELECT * FROM lenses'),dependencies,selection:{population:'all_years_theme_index',total_materials:total,selected_materials:dependencies.length,independent_materials:new Set(claims.filter(c=>c.evidence.origin!=='ai').map(c=>c.material_fingerprint)).size,omitted:Math.max(0,total-selected.length),limits:themeLimits}};
}
async function retryChanged(env:Env,j:ThemeJob){await stmt(env,`UPDATE theme_jobs SET state='pending',attempts=0,lease_token=NULL,dispatched_at=NULL,available_at=?,error_code='theme_context_changed' WHERE id=? AND lease_token=?`,now()+15000,j.id,j.lease_token).run();}
async function processSynthesis(env:Env,j:ThemeJob,fetcher?:typeof fetch){
 const input=await synthesisInput(env,j.target_id);if(input.theme.state!=='active'){await stmt(env,"UPDATE theme_jobs SET state='completed',lease_token=NULL WHERE id=? AND lease_token=?",j.id,j.lease_token).run();return;}
 const fingerprint=await digest(JSON.stringify({theme:input.theme,claims:input.claims,views:input.views,dependencies:input.dependencies,analysis_drafts:input.analysis_drafts}));
 const old=await stmt(env,'SELECT input_fingerprint FROM theme_revisions WHERE id=?',input.previous_id).first<{input_fingerprint:string}>();if(old?.input_fingerprint===fingerprint){await stmt(env,"UPDATE theme_jobs SET state='completed',lease_token=NULL WHERE id=? AND version=? AND lease_token=?",j.id,j.version,j.lease_token).run();return;}
 let result:Synthesis;try{result=input.claims.length?validateSynthesis(await response(env,'theme_synthesis_v1',synthesisSchema,synthesisInstructions+' 会話案analysis_draftsはAI仮説であり独立した証拠ではない。原claimsに裏付けられない説明を確定せず、未検証の問いとして扱う。',input,fetcher),input) as Synthesis:{changed:true,change_reason:'現在有効な原根拠がなくなったため、説明を保留しました。',understanding:[],changes:[],competing:[],conditions:[],questions:[],relations:[],theme_relations:[],view_proposal:null};}catch(e){if(e instanceof AiError)throw e;throw new AiError('invalid_theme_output');}
 // Preserve wording on no semantic change while accepting additional grounded references.
 if(!result.changed&&input.previous){for(const key of ['understanding','changes','competing','conditions','questions'] as const){const previous=input.previous[key];if(previous.some(x=>x.evidence.some(e=>!input.claims.some(c=>c.id===e.claim_id)))){result.changed=true;result.change_reason='根拠の変更を再評価しました。';break;}result[key]=previous.map(x=>({...x,evidence:result[key].find(y=>y.id===x.id)?.evidence||x.evidence}));}}
 const revision=id(),v=input.previous_version+1,all=result.understanding.concat(result.changes,result.competing,result.conditions,result.questions),claims=new Map(input.claims.map(c=>[c.id,c]));
 let guard=`EXISTS(SELECT 1 FROM theme_jobs WHERE id=? AND version=? AND state='running' AND lease_token=?) AND EXISTS(SELECT 1 FROM themes WHERE id=? AND version=? AND state='active') AND COALESCE((SELECT version FROM theme_syntheses WHERE theme_id=?),0)=?`;
 const values:(string|number|null)[]=[j.id,j.version,j.lease_token,input.theme.id,input.theme.version,input.theme.id,input.previous_version];
 for(const d of input.dependencies){guard+=' AND EXISTS(SELECT 1 FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version WHERE c.id=? AND c.version=? AND h.result=?)';values.push(d.capture_id,d.version,d.harvest);}
 if(result.view_proposal?.view_id){guard+=' AND EXISTS(SELECT 1 FROM views WHERE id=? AND version=?)';values.push(result.view_proposal.view_id,result.view_proposal.base_version);}
 const statements=[stmt(env,`INSERT INTO theme_revisions(id,theme_id,version,result,input_snapshot,input_fingerprint,processing_version,model,changed,change_reason,created_at) SELECT ?,?,?,?,?,?,'theme-synthesis/v1',?,?,?,? WHERE ${guard}`,revision,j.target_id,v,JSON.stringify(result),JSON.stringify(input),fingerprint,env.OPENAI_MODEL,result.changed?1:0,result.change_reason,now(),...values)];
 const exists='EXISTS(SELECT 1 FROM theme_revisions WHERE id=?)';
 for(const d of input.dependencies)statements.push(stmt(env,`INSERT INTO theme_dependencies SELECT ?,?,? WHERE ${exists}`,revision,d.capture_id,d.version,revision));
 for(const section of all)for(const e of section.evidence){const c=claims.get(e.claim_id)!;statements.push(stmt(env,`INSERT OR IGNORE INTO synthesis_evidence SELECT ?,?,?,?,?,?,?,? WHERE ${exists}`,revision,section.id,e.claim_id,c.capture_id,c.capture_version,e.quote,c.evidence.origin,e.role,revision));}
 for(const [i,r] of result.relations.entries())statements.push(stmt(env,`INSERT INTO theme_claim_relations SELECT ?,?,?,?,?,? WHERE ${exists}`,`${revision}:r${i}`,revision,r.from_id,r.to_id,r.type,JSON.stringify({...r,interpretation:'ai_hypothesis',organized_by:'ai'}),revision));
 for(const [i,r] of result.theme_relations.entries())statements.push(stmt(env,`INSERT INTO theme_relations SELECT ?,?,?,?,?,? WHERE ${exists}`,`${revision}:t${i}`,revision,j.target_id,r.theme_id,r.lens_id,JSON.stringify(r),revision));
 if(result.view_proposal){const p=result.view_proposal;const key=await proposalKey(p);statements.push(stmt(env,`INSERT INTO theme_proposals SELECT ?,?,?,?,?,?,?,?,?,'pending',? WHERE ${exists} AND NOT EXISTS(SELECT 1 FROM theme_overrides WHERE theme_id=? AND item_key=? AND action='hidden')`,id(),j.target_id,revision,p.view_id,p.base_version,p.from_text,p.to_text,p.reason,JSON.stringify({theme_id:j.target_id,revision_id:revision,dependencies:input.dependencies.map(({harvest,...d})=>d),evidence:p.evidence.map(e=>({...e,snapshot:claims.get(e.claim_id)}))}),now(),revision,j.target_id,key));}
 statements.push(stmt(env,`INSERT INTO theme_syntheses SELECT ?,?,? WHERE ${exists} ON CONFLICT(theme_id) DO UPDATE SET revision_id=excluded.revision_id,version=excluded.version`,j.target_id,revision,v,revision));
 statements.push(stmt(env,`UPDATE theme_jobs SET state='completed',lease_token=NULL,error_code=NULL WHERE id=? AND lease_token=? AND ${exists}`,j.id,j.lease_token,revision));
 const saved=await env.DB.batch(statements);if(!saved.at(-1)?.meta.changes)await retryChanged(env,j);
}
export async function processThemeJob(env:Env,jobId:string,fetcher?:typeof fetch){
 const permit=await stmt(env,'SELECT kind,target_id,version FROM theme_jobs WHERE id=?',jobId).first<{kind:string;target_id:string;version:number}>();if(!permit||!await allowedAI(env,permit.kind,permit.target_id,permit.version))return;
 const token=id(),j=await stmt(env,`UPDATE theme_jobs SET state='running',attempts=attempts+1,lease_token=?,lease_until=? WHERE id=? AND state='pending' AND available_at<=? RETURNING *`,token,now()+180000,jobId,now()).first<ThemeJob>();if(!j)return;
 try{if(j.kind==='membership')await processMembership(env,j,fetcher);else await processSynthesis(env,j,fetcher);}catch(e){const error=e instanceof AiError?e:new AiError('theme_processing_failed'),blocked=['ai_not_configured','daily_limit','subscription_reauth_required','subscription_sharing_usage_limit_exceeded'].includes(error.code),tomorrow=new Date();tomorrow.setUTCHours(24,0,0,0);await stmt(env,`UPDATE theme_jobs SET state=?,error_code=?,lease_token=NULL,dispatched_at=NULL,available_at=? WHERE id=? AND lease_token=?`,blocked?'blocked':error.retryable&&j.attempts<3?'pending':'failed',error.code,['daily_limit','subscription_sharing_usage_limit_exceeded'].includes(error.code)?tomorrow.getTime():now()+1000*2**j.attempts,j.id,token).run();}
}
export async function listThemes(env:Env){
 return {branches:await rows(env,"SELECT DISTINCT k.parent_id,k.child_id FROM knowledge_inputs k JOIN theme_syntheses s ON s.revision_id=k.parent_revision WHERE k.child_kind='theme' UNION SELECT parent_id,child_id FROM question_relations"),domains:await rows(env,'SELECT * FROM domains ORDER BY position'),themes:await rows(env,`SELECT NOT EXISTS(SELECT 1 FROM knowledge_inputs k JOIN theme_syntheses ks ON ks.revision_id=k.parent_revision WHERE k.child_kind='theme' AND k.child_id=t.id) AND NOT EXISTS(SELECT 1 FROM question_relations qr WHERE qr.child_id=t.id) AS is_tip,t.*, (SELECT count(*) FROM integration_runs i WHERE i.state='completed' AND json_extract(i.result_json,'$.theme_id')=t.id) AS integration_count, (SELECT json_group_array(domain_id) FROM theme_domains WHERE theme_id=t.id) AS domain_ids, (SELECT count(*) FROM current_theme_memberships m WHERE m.theme_id=t.id) AS material_count,r.result,r.changed,r.change_reason,r.created_at AS updated_at,j.state AS job_state,j.error_code,(COALESCE(json_extract(r.input_snapshot,'$.theme.version'),t.version)<>t.version OR EXISTS(SELECT 1 FROM theme_dependencies e LEFT JOIN captures c ON c.id=e.capture_id WHERE e.revision_id=s.revision_id AND (c.id IS NULL OR c.version<>e.capture_version OR EXISTS(SELECT 1 FROM theme_overrides o WHERE o.theme_id=t.id AND o.item_key='capture:'||e.capture_id AND o.action='hidden')))) AS stale FROM themes t LEFT JOIN theme_syntheses s ON s.theme_id=t.id LEFT JOIN theme_revisions r ON r.id=s.revision_id LEFT JOIN theme_jobs j ON j.kind='synthesis' AND j.target_id=t.id WHERE t.state='active' AND NOT EXISTS(SELECT 1 FROM theme_overrides o WHERE o.theme_id=t.id AND o.item_key='theme' AND o.action='hidden') ORDER BY COALESCE(r.created_at,0) DESC,t.created_at,t.id`)};
}
export async function captureThemes(env:Env,captureId:string){return rows(env,`SELECT t.id,t.question,m.reason FROM current_theme_memberships m JOIN themes t ON t.id=m.theme_id WHERE m.capture_id=? AND t.state='active'`,captureId);}
export async function readTheme(env:Env,themeId:string){
 const t=await stmt(env,'SELECT * FROM themes WHERE id=?',themeId).first<Theme>();if(!t)fail(404,'テーマが見つかりません。');if(t.merged_into)return {redirect:t.merged_into};
 const r=await stmt(env,'SELECT r.* FROM theme_syntheses s JOIN theme_revisions r ON r.id=s.revision_id WHERE s.theme_id=?',themeId).first<{id:string;result:string;version:number;input_snapshot:string}>();
 const material=await rows<Member>(env,'SELECT * FROM current_theme_memberships WHERE theme_id=? ORDER BY created_at DESC LIMIT 100',themeId);
 const evidence=r?await rows<{capture_id:string;capture_version:number;valid:number;claim_id:string;quote:string|null}>(env,`SELECT e.*,CASE WHEN c.version=e.capture_version AND NOT EXISTS(SELECT 1 FROM theme_overrides o WHERE o.theme_id=? AND o.item_key='capture:'||e.capture_id AND o.action='hidden') THEN 1 ELSE 0 END AS valid,c.page,s.title AS source_title FROM synthesis_evidence e LEFT JOIN captures c ON c.id=e.capture_id LEFT JOIN sources s ON s.id=c.source_id WHERE e.revision_id=?`,themeId,r.id):[];
 const issues=r?await rows<{capture_id:string;capture_version:number}>(env,`SELECT d.* FROM theme_dependencies d LEFT JOIN captures c ON c.id=d.capture_id WHERE d.revision_id=? AND (c.id IS NULL OR c.version<>d.capture_version OR EXISTS(SELECT 1 FROM theme_overrides o WHERE o.theme_id=? AND o.item_key='capture:'||d.capture_id AND o.action='hidden'))`,r.id,themeId):[],stale=issues.length>0||Boolean(r&&JSON.parse(r.input_snapshot).theme?.version!==t.version);
 const result=r?JSON.parse(r.result) as Synthesis:null;
 // An invalid quote is never presented as current evidence, even before regeneration.
 if(result)for(const key of ['understanding','changes','competing','conditions','questions'] as const)result[key]=result[key].map(x=>({...x,evidence:x.evidence.filter(e=>evidence.some(p=>p.claim_id===e.claim_id&&p.valid))}));
 const proposals=r&&!stale?await rows<{id:string;view_id:string|null;base_version:number|null;from_text:string;to_text:string;reason:string}>(env,`SELECT p.* FROM theme_proposals p LEFT JOIN views v ON v.id=p.view_id WHERE p.revision_id=? AND p.status='pending' AND (p.view_id IS NULL OR v.version=p.base_version)`,r.id):[];
 return {...await drilldownLinks(env,themeId),children:r?await rows(env,`SELECT k.*,COALESCE(t.question,json_extract(h.result,'$.summary'),'記録') AS title FROM knowledge_inputs k LEFT JOIN themes t ON k.child_kind='theme' AND t.id=k.child_id LEFT JOIN harvests h ON k.child_kind='capture' AND h.capture_id=k.child_id AND h.version=k.child_version WHERE k.parent_revision=?`,r.id):[],parents:await rows(env,`SELECT DISTINCT t.id,t.question FROM knowledge_inputs k JOIN theme_syntheses s ON s.revision_id=k.parent_revision JOIN themes t ON t.id=k.parent_id WHERE k.child_kind='theme' AND k.child_id=?`,themeId),theme:t,result,revision:r?.version||0,stale,evidence_issues:issues.map(e=>({capture_id:e.capture_id,version:e.capture_version})),evidence:evidence.filter(e=>e.valid),materials:material,job:await stmt(env,"SELECT state,error_code FROM theme_jobs WHERE kind='synthesis' AND target_id=?",themeId).first(),history:await rows(env,'SELECT id,version,changed,change_reason,created_at FROM theme_revisions WHERE theme_id=? AND changed=1 ORDER BY version DESC LIMIT 20',themeId),relations:r&&!stale?await rows(env,'SELECT * FROM theme_relations WHERE revision_id=?',r.id):[],proposals,views:await rows(env,'SELECT v.* FROM views v JOIN theme_view_links l ON l.view_id=v.id WHERE l.theme_id=?',themeId)};
}
async function proposalKey(p:{view_id:string|null;from_text:string;to_text:string}){return `proposal:${await digest(JSON.stringify([p.view_id,norm(p.from_text),norm(p.to_text)]))}`;}
export async function actThemeProposal(env:Env,themeId:string,input:Record<string,unknown>){
 const action=text(input.action,10),proposalId=text(input.proposal_id,100);if(!['adopt','hide'].includes(action))fail(400,'操作を確認してください。');
 const p=await stmt(env,`SELECT p.*,s.version AS synthesis_version FROM theme_proposals p JOIN theme_syntheses s ON s.revision_id=p.revision_id WHERE p.id=? AND p.theme_id=? AND p.status='pending'`,proposalId,themeId).first<{id:string;revision_id:string;view_id:string|null;base_version:number|null;from_text:string;to_text:string;reason:string;references_json:string}>();if(!p)fail(409,'案が更新されています。');
 if(action==='hide'){await env.DB.batch([stmt(env,"INSERT OR REPLACE INTO theme_overrides VALUES(?,?,'hidden',NULL,?)",themeId,await proposalKey(p),now()),stmt(env,"UPDATE theme_proposals SET status='hidden' WHERE id=?",p.id)]);return {ok:true};}
 const t=await readTheme(env,themeId);if('redirect' in t||t.stale)fail(409,'根拠が更新されています。');const viewId=p.view_id||id(),v=p.view_id?await stmt(env,'SELECT * FROM views WHERE id=?',p.view_id).first<View>():null;if(p.view_id&&(!v||v.version!==p.base_version||v.body.split(p.from_text).length!==2))fail(409,'見方が更新されています。');
 const body=v?v.body.replace(p.from_text,p.to_text):p.to_text,version=v?v.version+1:1,refs=JSON.parse(p.references_json),first=refs.dependencies[0];if(!first)fail(409,'有効な根拠がありません。');
 let guard=`EXISTS(SELECT 1 FROM theme_proposals p JOIN theme_syntheses s ON s.revision_id=p.revision_id WHERE p.id=? AND p.status='pending')`,values:(string|number|null)[]=[p.id];
 for(const d of refs.dependencies){guard+=' AND EXISTS(SELECT 1 FROM captures WHERE id=? AND version=?)';values.push(d.capture_id,d.version);}
 if(v){guard+=' AND EXISTS(SELECT 1 FROM views WHERE id=? AND version=?)';values.push(v.id,v.version);}
 const statements=[v?stmt(env,`UPDATE views SET body=?,version=version+1 WHERE id=? AND ${guard}`,body,viewId,...values):stmt(env,`INSERT INTO views SELECT ?,?,?,?,?,1,? WHERE ${guard}`,viewId,first.capture_id,`theme:${p.id}`,('theme'in t?t.theme.question:''),body,now(),...values),stmt(env,`INSERT INTO view_revisions SELECT ?,?,?,?,?,? WHERE ${guard}`,viewId,version,body,p.reason,p.references_json,now(),...values)];
 // View update itself changes the base guard; later writes use the new version and pending proposal.
 if(v)statements[1]=stmt(env,`INSERT INTO view_revisions SELECT ?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM views WHERE id=? AND version=? AND body=?) AND EXISTS(SELECT 1 FROM theme_proposals WHERE id=? AND status='pending')`,viewId,version,body,p.reason,p.references_json,now(),viewId,version,body,p.id);
 statements.push(stmt(env,`INSERT OR REPLACE INTO theme_view_links SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM view_revisions WHERE view_id=? AND version=?)`,themeId,viewId,p.reason,viewId,version),stmt(env,`UPDATE theme_proposals SET status='adopted' WHERE id=? AND EXISTS(SELECT 1 FROM view_revisions WHERE view_id=? AND version=?)`,p.id,viewId,version));
 const saved=await env.DB.batch(statements);if(!saved[0].meta.changes)fail(409,'見方または根拠が更新されています。');return {ok:true,view_id:viewId};
}

export async function themeMigrationStatus(env:Env){return {counts:await rows(env,`SELECT kind,state,count(*) AS count FROM theme_jobs GROUP BY kind,state`),unprocessed:(await stmt(env,`SELECT count(*) AS n FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version WHERE ?=1 AND NOT EXISTS(SELECT 1 FROM theme_jobs j WHERE j.kind='membership' AND j.target_id=c.id AND j.version=c.version AND j.state='completed')`).first<{n:number}>())?.n||0,paused:(await stmt(env,"SELECT value FROM settings WHERE key='theme_backfill_paused'").first<string>('value'))==='1',limits:themeLimits};}
export async function manageThemeMigration(env:Env,input:Record<string,unknown>){const action=text(input.action,20);if(!['pause','resume','retry'].includes(action))fail(400,'移行操作を確認してください。');if(action==='retry')await stmt(env,`UPDATE theme_jobs SET state='pending',attempts=0,error_code=NULL,available_at=?,dispatched_at=NULL WHERE id IN(SELECT id FROM theme_jobs WHERE state IN('failed','blocked') ORDER BY created_at LIMIT 20)`,now()).run();else{await stmt(env,"INSERT OR REPLACE INTO settings VALUES('theme_backfill_paused',?)",action==='pause'?'1':'0').run();if(action==='resume')await stmt(env,"UPDATE theme_jobs SET available_at=? WHERE kind='membership' AND created_at=0 AND state='pending'",now()).run();}if(!automaticAI(env)&&action!=='pause'){const caps=await rows<{id:string;version:number}>(env,`SELECT c.id,c.version FROM captures c JOIN harvests h ON h.capture_id=c.id AND h.version=c.version WHERE NOT EXISTS(SELECT 1 FROM theme_jobs j WHERE j.kind='membership' AND j.target_id=c.id AND j.version=c.version AND j.state='completed') ORDER BY c.created_at LIMIT 20`);for(const c of caps){await env.DB.batch([membershipJobStatement(env,c.id,c.version)]);await authorizeAI(env,'membership',c.id,c.version);}}return themeMigrationStatus(env);}
export async function editTheme(env:Env,themeId:string,input:Record<string,unknown>){const t=await stmt(env,'SELECT * FROM themes WHERE id=?',themeId).first<Theme>();if(!t||t.version!==Number(input.version))fail(409,'テーマが更新されています。');const question=typeof input.question==='string'?text(input.question,200).trim():t.question,scope=typeof input.scope==='string'?text(input.scope,1000).trim():t.scope,exclusions=typeof input.exclusions==='string'?text(input.exclusions,1000):t.exclusions;const content=Object.hasOwn(input,'content')?questionContent(input.content):t.content;if(!question)fail(400,'主題を入力してください。');const saved=await env.DB.batch([stmt(env,`INSERT INTO theme_history SELECT ?,?,'edit',?,?,? WHERE EXISTS(SELECT 1 FROM themes WHERE id=? AND version=?)`,id(),themeId,text(input.reason||'本人によるテーマの訂正',1000),JSON.stringify(t),now(),themeId,t.version),stmt(env,`UPDATE themes SET question=?,scope=?,exclusions=?,content=?,version=version+1 WHERE id=? AND version=?`,question,scope,exclusions,content,themeId,t.version)]);if(!saved[1].meta.changes)fail(409,'テーマが更新されています。');return readTheme(env,themeId);}
export async function overrideTheme(env:Env,themeId:string,input:Record<string,unknown>){const detail=await readTheme(env,themeId);if('redirect'in detail)fail(409,'テーマが統合されています。');const key=text(input.item_key,150),action=text(input.action,20),member=key.startsWith('capture:')?await stmt(env,'SELECT capture_id FROM theme_memberships WHERE theme_id=? AND capture_id=?',themeId,key.slice(8)).first():null;if(!['hidden','restore'].includes(action)||!(key==='theme'||key.startsWith('capture:')&&Boolean(member)))fail(400,'対象を確認してください。');if(action==='restore')await stmt(env,'DELETE FROM theme_overrides WHERE theme_id=? AND item_key=?',themeId,key).run();else await stmt(env,"INSERT OR REPLACE INTO theme_overrides VALUES(?,?,'hidden',NULL,?)",themeId,key,now()).run();await dirty(env,[themeId]);return {ok:true};}
export async function mergeTheme(env:Env,themeId:string,input:Record<string,unknown>){const targetId=text(input.target_id,100),reason=text(input.reason,1000).trim(),from=await stmt(env,'SELECT * FROM themes WHERE id=?',themeId).first<Theme>(),to=await stmt(env,"SELECT * FROM themes WHERE id=? AND state='active'",targetId).first<Theme>();if(!from||!to||from.id===to.id||from.version!==Number(input.version)||!reason)fail(409,'統合先、版、理由を確認してください。');const guard="EXISTS(SELECT 1 FROM themes WHERE id=? AND version=? AND state IN('active','candidate')) AND EXISTS(SELECT 1 FROM themes WHERE id=? AND version=? AND state='active')",values=[from.id,from.version,to.id,to.version];
 const statements=[stmt(env,`INSERT INTO theme_history SELECT ?,?,'merge',?,?,? WHERE ${guard}`,id(),from.id,reason,JSON.stringify({theme:from,target:to}),now(),...values),stmt(env,`INSERT OR IGNORE INTO theme_memberships SELECT ?,m.capture_id,m.capture_version,m.claim_ids,m.reason,m.role,m.fingerprint,m.processing_version,m.created_at FROM theme_memberships m WHERE m.theme_id=? AND ${guard}`,to.id,from.id,...values),stmt(env,`INSERT OR IGNORE INTO theme_domains SELECT ?,domain_id FROM theme_domains WHERE theme_id=? AND ${guard}`,to.id,from.id,...values),stmt(env,`INSERT OR IGNORE INTO theme_view_links SELECT ?,view_id,reason FROM theme_view_links WHERE theme_id=? AND ${guard}`,to.id,from.id,...values),stmt(env,`INSERT OR IGNORE INTO theme_overrides SELECT ?,item_key,action,value,created_at FROM theme_overrides WHERE theme_id=? AND ${guard}`,to.id,from.id,...values),stmt(env,`DELETE FROM theme_memberships WHERE theme_id=? AND ${guard}`,from.id,...values),stmt(env,`UPDATE themes SET state='merged',merged_into=?,version=version+1 WHERE id=? AND ${guard}`,to.id,from.id,...values)];const saved=await env.DB.batch(statements);if(!saved.at(-1)?.meta.changes)fail(409,'テーマが更新されています。');await dirty(env,[to.id]);return {ok:true,redirect:to.id};}
