import {stmt,rows,fail,id,now,text,digest} from './core.ts';
type Row=Record<string,string|number|null>;
type Snapshot=Record<string,Row[]>;
const related=['theme_domains','theme_memberships','theme_view_links','theme_overrides','theme_member_lenses'];
async function snapshot(env:Env,ids:string[]):Promise<Snapshot>{const out:Snapshot={themes:await rows<Row>(env,'SELECT * FROM themes WHERE id IN(SELECT value FROM json_each(?)) ORDER BY id',JSON.stringify(ids))};for(const table of related)out[table]=await rows<Row>(env,`SELECT * FROM ${table} WHERE theme_id IN(SELECT value FROM json_each(?)) ORDER BY rowid`,JSON.stringify(ids));return out;}
function canonical(s:Snapshot){return JSON.stringify(Object.fromEntries(Object.entries(s).map(([k,v])=>[k,v.map(r=>JSON.stringify(r)).sort()])));}
const unique=(items:Row[],keys:string[])=>[...new Map(items.map(r=>[JSON.stringify(keys.map(k=>r[k])),r])).values()];
export async function readThemeChange(env:Env,changeId:string){const change=await stmt(env,'SELECT * FROM theme_changes WHERE id=?',changeId).first<Row>();if(!change)fail(404,'theme_change_missing');return {...change,before:JSON.parse(String(change.before_json)),after:JSON.parse(String(change.after_json)),impact:{preserves_originals:true,preserves_user_views_and_revisions:true,ai_called:false}} as unknown as Row&{before:Snapshot;after:Snapshot;impact:Record<string,boolean>};}
export async function proposeThemeChange(env:Env,a:Record<string,unknown>){
 const themeId=text(a.id,100),reason=text(a.reason,1000).trim(),action=text(a.action,20);if(!reason||!['edit','merge','split','candidate','archive','aliases'].includes(action))fail(400,'invalid_theme_change');
 const source=await stmt(env,'SELECT * FROM themes WHERE id=?',themeId).first<Row>();if(!source||source.version!==Number(a.version)||!['active','candidate'].includes(String(source.state)))fail(409,'theme_version_conflict');
 const newId=`theme:${id()}`,targetId=action==='merge'?text(a.target_id,100):['split','candidate'].includes(action)?newId:null,ids=[themeId,...targetId?[targetId]:[]];
 const before=await snapshot(env,ids);if(Object.values(before).reduce((n,x)=>n+x.length,0)>300)fail(413,'theme_change_scope_limit');
 const after=structuredClone(before),from=after.themes.find(t=>t.id===themeId)!;from.version=Number(from.version)+1;
 if(action==='merge'){
  const target=after.themes.find(t=>t.id===targetId);if(!target||target.id===themeId||target.version!==Number(a.target_version)||target.state!=='active')fail(409,'target_theme_version_conflict');target.version=Number(target.version)+1;from.state='merged';from.merged_into=targetId!;
  for(const table of related){const sourceRows=after[table].filter(r=>r.theme_id===themeId&&!(table==='theme_overrides'&&r.item_key==='theme'));after[table]=[...sourceRows.map(r=>({...r,theme_id:targetId!})),...after[table].filter(r=>r.theme_id!==themeId)];const keys=table==='theme_domains'?['theme_id','domain_id']:table==='theme_memberships'?['theme_id','capture_id']:table==='theme_view_links'?['theme_id','view_id']:table==='theme_overrides'?['theme_id','item_key']:['theme_id','capture_id','lens_id'];after[table]=unique(after[table],keys);}
 }else if(action==='split'||action==='candidate'){
  const question=text(a.question,200).trim(),scope=text(a.scope,1000).trim();if(!question||!scope)fail(400,'theme_question_and_scope_required');
  after.themes.push({...source,id:newId,question,scope,exclusions:typeof a.exclusions==='string'?text(a.exclusions,1000):'',version:1,state:action==='candidate'?'candidate':'active',merged_into:null,created_by:'user',created_at:now(),aliases:'[]'});
  const domains=Array.isArray(a.domain_ids)?a.domain_ids:before.theme_domains.filter(r=>r.theme_id===themeId).map(r=>r.domain_id);if(domains.length<1||domains.length>6||domains.some(d=>typeof d!=='string'||!d))fail(400,'invalid_domains');for(const d of new Set(domains)){if(!await stmt(env,'SELECT id FROM domains WHERE id=?',String(d)).first())fail(400,'unknown_domain');after.theme_domains.push({theme_id:newId,domain_id:String(d)});}
  if(action==='split'){const selected=Array.isArray(a.capture_ids)?a.capture_ids:[];if(!selected.length||selected.length>20||new Set(selected).size!==selected.length||selected.some(c=>!before.theme_memberships.some(m=>m.theme_id===themeId&&m.capture_id===c)))fail(400,'invalid_split_members');for(const table of ['theme_memberships','theme_member_lenses'])after[table]=after[table].map(r=>r.theme_id===themeId&&selected.includes(r.capture_id)?{...r,theme_id:newId}:r);}
 }else if(action==='archive'){from.state='archived';}
 else{if(action==='aliases'){if(!Array.isArray(a.aliases)||a.aliases.length>12||a.aliases.some(x=>typeof x!=='string'||x.length>100))fail(400,'invalid_aliases');from.aliases=JSON.stringify([...new Set(a.aliases)]);}else{for(const k of ['question','scope','exclusions'])if(typeof a[k]==='string')from[k]=text(a[k],k==='question'?200:1000).trim();if(!from.question||!from.scope)fail(400,'theme_question_and_scope_required');}}
 const changeId=id();await stmt(env,'INSERT INTO theme_changes(id,theme_id,action,reason,theme_ids_json,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?,?)',changeId,themeId,action,reason,JSON.stringify(ids),JSON.stringify(before),JSON.stringify(after),now()).run();return readThemeChange(env,changeId);
}
// Compare every captured row inside the same D1 batch as the mutation, not just at preview time.
function snapshotGuard(ids:string[],current:Snapshot){let sql='1';const values:(string|number|null)[]=[];for(const [table,data] of Object.entries(current)){const owner=table==='themes'?'id':'theme_id';sql+=` AND (SELECT count(*) FROM ${table} WHERE ${owner} IN(SELECT value FROM json_each(?)))=?`;values.push(JSON.stringify(ids),data.length);if(data.length){const cols=Object.keys(data[0]);sql+=` AND NOT EXISTS(SELECT 1 FROM json_each(?) j WHERE NOT EXISTS(SELECT 1 FROM ${table} t WHERE ${cols.map(k=>`t.${k} IS json_extract(j.value,'$.${k}')`).join(' AND ')}))`;values.push(JSON.stringify(data));}}return {sql,values};}
export async function applyThemeChange(env:Env,changeId:string,undo=false){
 const change=await readThemeChange(env,changeId),state=undo?'undone':'applied';if(change.state===state)return {ok:true,duplicate:true,id:changeId};if(change.state!==(undo?'applied':'proposed'))fail(409,'theme_change_state_conflict');
 const ids=JSON.parse(String(change.theme_ids_json)) as string[],current=await snapshot(env,ids),expected=undo?JSON.parse(String(change.applied_json)):change.before as Snapshot;
 if(canonical(current)!==canonical(expected))fail(409,'theme_change_context_changed');const desired=structuredClone(undo?change.before as Snapshot:change.after as Snapshot);
 if(undo){for(const theme of desired.themes)theme.version=Number(current.themes.find(t=>t.id===theme.id)!.version)+1;for(const theme of current.themes)if(!desired.themes.some(t=>t.id===theme.id))desired.themes.push({...theme,state:'archived',version:Number(theme.version)+1});}
 const guard=snapshotGuard(ids,current),token=id(),active='EXISTS(SELECT 1 FROM theme_changes WHERE id=? AND state=? AND '+(undo?'undo_json':'applied_json')+'=?)',activeValues=[changeId,state,JSON.stringify(desired)];
 const writes=[stmt(env,`UPDATE theme_changes SET state=?,${undo?'undone_at':'applied_at'}=?,${undo?'undo_json':'applied_json'}=? WHERE id=? AND state=? AND ${guard.sql}`,state,now(),JSON.stringify(desired),changeId,change.state,...guard.values)];
 for(const t of desired.themes){const cols=Object.keys(t);if(current.themes.some(x=>x.id===t.id))writes.push(stmt(env,`UPDATE themes SET ${cols.filter(k=>k!=='id').map(k=>k+'=?').join(',')} WHERE id=? AND ${active}`,...cols.filter(k=>k!=='id').map(k=>t[k]),t.id,...activeValues));else writes.push(stmt(env,`INSERT INTO themes(${cols.join(',')}) SELECT ${cols.map(()=>'?').join(',')} WHERE ${active}`,...cols.map(k=>t[k]),...activeValues));}
 for(const table of related){writes.push(stmt(env,`DELETE FROM ${table} WHERE theme_id IN(SELECT value FROM json_each(?)) AND ${active}`,JSON.stringify(ids),...activeValues));const data=desired[table];if(data.length){const cols=Object.keys(data[0]);writes.push(stmt(env,`INSERT INTO ${table}(${cols.join(',')}) SELECT ${cols.map(k=>`json_extract(j.value,'$.${k}')`).join(',')} FROM json_each(?) j WHERE ${active}`,JSON.stringify(data),...activeValues));}}
 writes.push(stmt(env,`INSERT INTO theme_history SELECT ?,?,?,?, ?,? WHERE ${active}`,token,String(change.theme_id),undo?'undo':String(change.action),String(change.reason),JSON.stringify(current),now(),...activeValues),stmt(env,`DELETE FROM explicit_ai_actions WHERE kind='synthesis' AND target_id IN(SELECT value FROM json_each(?)) AND ${active}`,JSON.stringify(ids),...activeValues));
 const saved=await env.DB.batch(writes);if(!saved[0].meta.changes)fail(409,'theme_change_context_changed');return {ok:true,id:changeId,state,theme_ids:ids,needs_explicit_rebuild:true,ai_called:false};
}
